import assert from 'node:assert/strict';
import {createBlockId,createMemoryRegionId,createValueId} from '../../js/core/identity/index.js';
const functionId='function_phase3_fixture',binaryId='bin_phase3_fixture';
const blockA=createBlockId({functionId,canonicalBlockIdentity:{entryEntityId:'entity_start',address:'0x1000'}});
const blockB=createBlockId({canonicalBlockIdentity:{address:'0x1000',entryEntityId:'entity_start'},functionId});
assert.equal(blockA,blockB,'BlockId must ignore object insertion order');
assert.notEqual(blockA,createBlockId({functionId,canonicalBlockIdentity:{entryEntityId:'entity_other',address:'0x1000'}}),'BlockId must use canonical block identity, not array position');
const firstDefinition=createValueId({functionId,canonicalDefinitionIdentity:{sourceEntityId:'node-1',outputIndex:0}});
assert.equal(firstDefinition,createValueId({canonicalDefinitionIdentity:{outputIndex:0,sourceEntityId:'node-1'},functionId}));
assert.notEqual(firstDefinition,createValueId({functionId,canonicalDefinitionIdentity:{sourceEntityId:'node-2',outputIndex:0}}),'separate definitions require separate ValueIds');
const stackRegion=createMemoryRegionId({functionId,binaryId,regionKind:'stack-fixed',canonicalRegionIdentity:{frameOffset:-16,widthBits:8}});
assert.equal(stackRegion,createMemoryRegionId({regionKind:'stack-fixed',canonicalRegionIdentity:{widthBits:8,frameOffset:-16},binaryId,functionId}));
const unknownA=createMemoryRegionId({functionId,binaryId,regionKind:'unknown',canonicalRegionIdentity:{uncertaintySource:'store-1',partition:0}});
const unknownB=createMemoryRegionId({functionId,binaryId,regionKind:'unknown',canonicalRegionIdentity:{uncertaintySource:'store-2',partition:0}});
assert.notEqual(unknownA,unknownB,'uncertain regions must not collapse into one guessed identity');
assert.throws(()=>createBlockId({functionId}),/block-canonical-identity-required/);
assert.throws(()=>createValueId({functionId}),/value-definition-identity-required/);
assert.throws(()=>createMemoryRegionId({functionId,regionKind:'unknown'}),/memory-region-identity-required/);
assert.throws(()=>createMemoryRegionId({regionKind:'unknown',canonicalRegionIdentity:'u1'}),/memory-region-scope-required/);
console.log('semantic-v2 identity contracts: PASS');
