import { createX86EffectContext, x86MemoryFaults } from './common.js';
import { x86EffectiveAddressExpression } from './addressing.js';
import { readX86VectorOperand, writeX86VectorRegister, x86VectorEncodingInfo } from './simd.js';

const SCALAR_MOVES = new Map([['movss',{scalarWidthBits:32,format:'binary32'}],['movsd',{scalarWidthBits:64,format:'binary64'}]]);
const SCALAR_ARITHMETIC = new Map([
  ['addss',{operation:'add',scalarWidthBits:32,format:'binary32'}],['addsd',{operation:'add',scalarWidthBits:64,format:'binary64'}],
  ['subss',{operation:'sub',scalarWidthBits:32,format:'binary32'}],['subsd',{operation:'sub',scalarWidthBits:64,format:'binary64'}],
  ['mulss',{operation:'mul',scalarWidthBits:32,format:'binary32'}],['mulsd',{operation:'mul',scalarWidthBits:64,format:'binary64'}],
  ['divss',{operation:'div',scalarWidthBits:32,format:'binary32'}],['divsd',{operation:'div',scalarWidthBits:64,format:'binary64'}],
]);
const SCALAR_SQRT = new Map([['sqrtss',{scalarWidthBits:32,format:'binary32'}],['sqrtsd',{scalarWidthBits:64,format:'binary64'}]]);
const SCALAR_COMPARE = new Map([
  ['ucomiss',{scalarWidthBits:32,format:'binary32',signaling:'snan-only'}],['ucomisd',{scalarWidthBits:64,format:'binary64',signaling:'snan-only'}],
  ['comiss',{scalarWidthBits:32,format:'binary32',signaling:'nan'}],['comisd',{scalarWidthBits:64,format:'binary64',signaling:'nan'}],
]);
const PACKED_ARITHMETIC = new Map([
  ['addps',{operation:'add',elementWidthBits:32,format:'binary32'}],['addpd',{operation:'add',elementWidthBits:64,format:'binary64'}],
  ['subps',{operation:'sub',elementWidthBits:32,format:'binary32'}],['subpd',{operation:'sub',elementWidthBits:64,format:'binary64'}],
  ['mulps',{operation:'mul',elementWidthBits:32,format:'binary32'}],['mulpd',{operation:'mul',elementWidthBits:64,format:'binary64'}],
  ['divps',{operation:'div',elementWidthBits:32,format:'binary32'}],['divpd',{operation:'div',elementWidthBits:64,format:'binary64'}],
]);
const CONVERSIONS = new Set(['cvtss2sd','cvtsd2ss','cvtsi2ss','cvtsi2sd','cvttss2si','cvttsd2si']);
const X87_FAMILIES = new Set(['fld','fld1','fldz','fst','fstp','fild','fist','fistp','fadd','faddp','fiadd','fsub','fsubp','fisub','fsubr','fsubrp','fmul','fmulp','fimul','fdiv','fdivp','fidiv','fdivr','fdivrp','fcom','fcomp','fcompp','fucom','fucomp','fucompp','fxch','fnstcw','fldcw','fnstsw','fwait','wait','fsqrt','frndint','fchs','fabs','fscale','fprem','fprem1','fyl2x','f2xm1']);

function baseFamily(family){return family.startsWith('v')?family.slice(1):family;}
function isVector(operand){return operand?.type==='register'&&operand.register?.kind==='vector';}
function physicalId(operand){return isVector(operand)?operand.register.physicalId:null;}
function unique(values){return [...new Set(values.filter(Boolean))].sort();}
const FP_VECTOR_PP=new Map([['movss',2],['movsd',3],['addss',2],['addsd',3],['subss',2],['subsd',3],['mulss',2],['mulsd',3],['divss',2],['divsd',3],['sqrtss',2],['sqrtsd',3],['ucomiss',0],['ucomisd',1],['comiss',0],['comisd',1],['addps',0],['addpd',1],['subps',0],['subpd',1],['mulps',0],['mulpd',1],['divps',0],['divpd',1],['cvtss2sd',2],['cvtsd2ss',3],['cvtsi2ss',2],['cvtsi2sd',3],['cvttss2si',2],['cvttsd2si',3]]);

function validateEncoding(ctx,family,scalar=false){
  const encoding=x86VectorEncodingInfo(ctx.instruction);
  if(!encoding.valid)return{error:ctx.partial('x86-fp-vector-prefix-metadata-malformed',['registers','other'],{metadata:{family:'fp',operation:family}})};
  if(encoding.kind!=='legacy'){const expectedPp=FP_VECTOR_PP.get(baseFamily(family));if(expectedPp==null||encoding.opcodeMap!==1||encoding.mandatoryPrefixCode!==expectedPp)return{error:ctx.partial('x86-fp-vector-prefix-family-mismatch',['registers','other'],{metadata:{family:'fp',operation:family,expectedOpcodeMap:1,actualOpcodeMap:encoding.opcodeMap,expectedMandatoryPrefixCode:expectedPp,actualMandatoryPrefixCode:encoding.mandatoryPrefixCode}})};}
  if(encoding.kind==='evex')return{error:ctx.partial('x86-fp-evex-physical-state-unmodelled',['registers','faults','other'],{metadata:{family:'fp',operation:family,vectorPrefixKind:'evex',vectorWidthBits:encoding.vectorWidthBits,maskRegister:encoding.maskRegister,maskSemantics:encoding.maskRegister?(encoding.zeroing?'zero':'merge'):'none',broadcastOrRounding:encoding.broadcastOrRounding,sharedDependencyRequired:['x86-physical-zmm0-31','x86-opmask-k0-7','decoded-evex-fields']}})};
  if(family.startsWith('v')!==(encoding.kind==='vex'))return{error:ctx.partial('x86-fp-family-encoding-mismatch',['registers','other'],{metadata:{family:'fp',operation:family,encodingKind:encoding.kind}})};
  if(scalar&&encoding.kind==='vex'&&encoding.vectorWidthBits!==128)return{error:ctx.partial('x86-fp-vex-scalar-width-not-proven',['registers','other'],{metadata:{family:'fp',operation:family,encodedVectorWidthBits:encoding.vectorWidthBits}})};
  return{encoding};
}

function foundationAddress(ctx,operand){const memory=operand?.type==='memory'?operand.memory:null;if(!memory||memory.addressSizeBits!==64||memory.segment!=null)return null;return x86EffectiveAddressExpression(ctx.instruction,operand);}
function integrationPartial(ctx,family,categories=['memory','registers']){return ctx.partial('x86-fp-memory-address-requires-p5-2-integration',categories,{metadata:{family:'fp',operation:family,classification:'P5-I-INTEGRATION-REQUIRED'}});}

function readScalar(ctx,operand,widthBits){
  if(isVector(operand)){if(operand.widthBits!==128)return null;const vector=ctx.readRegister(operand);if(!vector)return null;return{value:ctx.valueOp('extract',[vector],widthBits,{lsb:0,widthBits,sourceView:operand.register.id,scalarLane:true}),registerId:physicalId(operand),possibleFaults:[],source:'vector-register'};}
  if(operand?.type==='memory'){if(operand.widthBits!==widthBits)return null;const address=foundationAddress(ctx,operand);if(!address)return{integrationRequired:true};const value=ctx.readMemory(address.expression,widthBits,{space:address.space,metadata:{...address.metadata,scalarFp:true}});return{value,registerId:null,possibleFaults:x86MemoryFaults('read',widthBits),source:'memory'};}
  return null;
}

function combineScalar(ctx,mergeSource,scalarValue,scalarBits){const low=ctx.readRegister(mergeSource);return low?ctx.valueOp('insert',[low,scalarValue],128,{lsb:0,widthBits:scalarBits,physicalBits:128,view:mergeSource.register.id,scalarLane:true,preserveBits:`127:${scalarBits}`}):null;}
function destinationShape(ctx,encoding,destination,mergeSource,scalarValue,scalarBits,zeroRemainder=false){if(!isVector(destination)||destination.widthBits!==128)return false;const low128=zeroRemainder?ctx.coerce(scalarValue,scalarBits,128,false):(isVector(mergeSource)&&mergeSource.widthBits===128?combineScalar(ctx,mergeSource,scalarValue,scalarBits):null);return low128?writeX86VectorRegister(ctx,destination,low128,encoding,128):false;}

function fpDetail(operation){return Object.freeze({instructionFamily:operation,missingCanonicalState:Object.freeze(['MXCSR.rounding-control','MXCSR.exception-mask-status','MXCSR.denormals-are-zero','MXCSR.flush-to-zero']),exactness:'visible destination shape is known; complete FP result/status/fault behavior is not representable',p5iRequirement:'add canonical x86 FP environment state/effects before promoting FP arithmetic, conversion, or compare to global exactness'});}
function fpFault(operation,signaling='operation-dependent'){return Object.freeze({kind:'x86-simd-floating-point-exception',condition:{kind:'mxcsr-exception-state-unmodelled',operation,signaling},detail:{exceptionClass:'#XM',maskState:'MXCSR-unmodelled'}});}
function fpPartial(ctx,family,metadata,faults=[],categories=['registers','faults','other']){return ctx.partial('x86-fp-environment-state-unmodelled',categories,{family:'fp',possibleFaults:faults,detail:fpDetail(family),metadata:{operation:family,fpEnvironmentModeled:false,...metadata}});}

function liftScalarMove(ctx,family,encoding,spec){
  const bits=spec.scalarWidthBits,[destination,source]=ctx.operands;
  if(encoding.kind==='legacy'){
    if(isVector(destination)){const input=readScalar(ctx,source,bits);if(input?.integrationRequired)return integrationPartial(ctx,family);if(!input)return ctx.partial(`x86-${family}-source-unmodelled`,['registers','memory']);const zeroRemainder=source?.type==='memory';if(!destinationShape(ctx,encoding,destination,destination,input.value,bits,zeroRemainder))return ctx.partial(`x86-${family}-destination-unmodelled`,['registers']);return ctx.finish({family:'fp',possibleFaults:input.possibleFaults,metadata:{operation:family,scalarWidthBits:bits,sourceKind:input.source,xmmBitsAboveScalar:zeroRemainder?'zero':'preserved',upperLaneBehavior:'preserve-upper-128'}});}
    if(destination?.type==='memory'&&isVector(source)){if(destination.widthBits!==bits)return ctx.partial(`x86-${family}-store-width-unmodelled`,['memory','registers']);const address=foundationAddress(ctx,destination);if(!address)return integrationPartial(ctx,family);const scalar=readScalar(ctx,source,bits);if(!scalar)return ctx.partial(`x86-${family}-store-source-unmodelled`,['registers','memory']);ctx.writeMemory(address.expression,bits,scalar.value,{space:address.space,metadata:{...address.metadata,scalarFp:true}});return ctx.finish({family:'fp',possibleFaults:x86MemoryFaults('write',bits),metadata:{operation:family,scalarWidthBits:bits,destination:'memory',memoryWidthBits:bits}});}
    return ctx.partial(`x86-${family}-operand-shape-unmodelled`,['registers','memory']);
  }
  if(ctx.operands.length===3&&isVector(ctx.operands[0])&&isVector(ctx.operands[1])){const[d,m,s]=ctx.operands,input=readScalar(ctx,s,bits);if(input?.integrationRequired)return integrationPartial(ctx,family);if(!input||!destinationShape(ctx,encoding,d,m,input.value,bits,false))return ctx.partial(`x86-${family}-vex-register-form-unmodelled`,['registers','memory']);return ctx.finish({family:'fp',possibleFaults:input.possibleFaults,metadata:{operation:family,scalarWidthBits:bits,sourceKind:input.source,xmmBitsAboveScalar:'from-vex-merge-source',upperLaneBehavior:'zero-upper-128'}});}
  if(ctx.operands.length===2&&isVector(ctx.operands[0])&&ctx.operands[1]?.type==='memory'){const[d,s]=ctx.operands,input=readScalar(ctx,s,bits);if(input?.integrationRequired)return integrationPartial(ctx,family);if(!input||!destinationShape(ctx,encoding,d,d,input.value,bits,true))return ctx.partial(`x86-${family}-vex-load-unmodelled`,['registers','memory']);return ctx.finish({family:'fp',possibleFaults:input.possibleFaults,metadata:{operation:family,scalarWidthBits:bits,sourceKind:'memory',xmmBitsAboveScalar:'zero',upperLaneBehavior:'zero-upper-128'}});}
  if(ctx.operands.length===2&&ctx.operands[0]?.type==='memory'&&isVector(ctx.operands[1])){const[d,s]=ctx.operands;if(d.widthBits!==bits)return ctx.partial(`x86-${family}-vex-store-width-unmodelled`,['memory','registers']);const address=foundationAddress(ctx,d);if(!address)return integrationPartial(ctx,family);const scalar=readScalar(ctx,s,bits);if(!scalar)return ctx.partial(`x86-${family}-vex-store-source-unmodelled`,['registers','memory']);ctx.writeMemory(address.expression,bits,scalar.value,{space:address.space,metadata:{...address.metadata,scalarFp:true}});return ctx.finish({family:'fp',possibleFaults:x86MemoryFaults('write',bits),metadata:{operation:family,scalarWidthBits:bits,destination:'memory',memoryWidthBits:bits,encodingKind:'vex'}});}
  return ctx.partial(`x86-${family}-vex-operand-shape-unmodelled`,['registers','memory']);
}

function scalarArithmeticOperands(ctx,encoding,bits){
  if(encoding.kind==='legacy'){const[d,s]=ctx.operands;if(!isVector(d))return null;const left=readScalar(ctx,d,bits),right=readScalar(ctx,s,bits);if(left?.integrationRequired||right?.integrationRequired)return{integrationRequired:true};return left&&right?{destination:d,mergeSource:d,left,right}:null;}
  const[d,a,b]=ctx.operands;if(!isVector(d)||!isVector(a))return null;const left=readScalar(ctx,a,bits),right=readScalar(ctx,b,bits);if(left?.integrationRequired||right?.integrationRequired)return{integrationRequired:true};return left&&right?{destination:d,mergeSource:a,left,right}:null;
}

function liftScalarArithmetic(ctx,family,encoding,spec){const operands=scalarArithmeticOperands(ctx,encoding,spec.scalarWidthBits);if(operands?.integrationRequired)return integrationPartial(ctx,family,['memory','registers','faults','other']);if(!operands)return ctx.partial(`x86-${family}-operand-shape-unmodelled`,['registers','memory','faults','other']);const result=ctx.intrinsic('x86.fp.scalar-arithmetic',[operands.left.value,operands.right.value],[spec.scalarWidthBits],{registersRead:unique([operands.left.registerId,operands.right.registerId]),registersWritten:[operands.destination.register.physicalId],determinism:'nondeterministic',symbolicDetail:'summary-only',metadata:{operation:spec.operation,format:spec.format,scalarWidthBits:spec.scalarWidthBits,encodingKind:encoding.kind,fpEnvironmentDependency:'MXCSR',exactArchitecturalSummary:false}})[0];if(!destinationShape(ctx,encoding,operands.destination,operands.mergeSource,result,spec.scalarWidthBits,false))return ctx.partial(`x86-${family}-destination-unmodelled`,['registers','faults','other']);return fpPartial(ctx,family,{scalarWidthBits:spec.scalarWidthBits,format:spec.format,encodingKind:encoding.kind,upperLaneBehavior:encoding.kind==='vex'?'zero-upper-128':'preserve-upper-128'},[...operands.left.possibleFaults,...operands.right.possibleFaults,fpFault(family)]);}

function liftScalarSqrt(ctx,family,encoding,spec){let d,m,s;if(encoding.kind==='legacy'){[d,s]=ctx.operands;m=d;}else[d,m,s]=ctx.operands;if(!isVector(d)||!isVector(m))return ctx.partial(`x86-${family}-operand-shape-unmodelled`,['registers','memory','faults','other']);const input=readScalar(ctx,s,spec.scalarWidthBits);if(input?.integrationRequired)return integrationPartial(ctx,family,['memory','registers','faults','other']);if(!input)return ctx.partial(`x86-${family}-source-unmodelled`,['registers','memory','faults','other']);const result=ctx.intrinsic('x86.fp.scalar-sqrt',[input.value],[spec.scalarWidthBits],{registersRead:unique([input.registerId,physicalId(m)]),registersWritten:[d.register.physicalId],determinism:'nondeterministic',symbolicDetail:'summary-only',metadata:{operation:'sqrt',format:spec.format,scalarWidthBits:spec.scalarWidthBits,fpEnvironmentDependency:'MXCSR',exactArchitecturalSummary:false}})[0];if(!destinationShape(ctx,encoding,d,m,result,spec.scalarWidthBits,false))return ctx.partial(`x86-${family}-destination-unmodelled`,['registers','faults','other']);return fpPartial(ctx,family,{scalarWidthBits:spec.scalarWidthBits,format:spec.format,encodingKind:encoding.kind},[...input.possibleFaults,fpFault(family)]);}

function liftScalarCompare(ctx,family,spec){const[a,b]=ctx.operands,left=readScalar(ctx,a,spec.scalarWidthBits),right=readScalar(ctx,b,spec.scalarWidthBits);if(left?.integrationRequired||right?.integrationRequired)return integrationPartial(ctx,family,['memory','flags','faults','other']);if(!left||!right)return ctx.partial(`x86-${family}-operand-shape-unmodelled`,['registers','memory','flags','faults','other']);const outputs=ctx.intrinsic('x86.fp.scalar-compare-flags',[left.value,right.value],[1,1,1],{registersRead:unique([left.registerId,right.registerId]),determinism:'input-dependent',symbolicDetail:'summary-only',metadata:{operation:family,format:spec.format,scalarWidthBits:spec.scalarWidthBits,outputs:['ZF','PF','CF'],ordered:{ZF:0,PF:0,CF:'lhs<rhs'},equal:{ZF:1,PF:0,CF:0},unordered:{ZF:1,PF:1,CF:1},signaling:spec.signaling,fpEnvironmentDependency:'MXCSR.exception-mask-status',exactVisibleFlagRule:true}});ctx.writeFlag('ZF',outputs[0],{operation:family,unorderedAware:true});ctx.writeFlag('PF',outputs[1],{operation:family,unorderedAware:true});ctx.writeFlag('CF',outputs[2],{operation:family,unorderedAware:true});for(const flag of ['OF','SF','AF'])ctx.writeFlag(flag,ctx.constant(1,0n),{operation:family,architecturallyCleared:true});return fpPartial(ctx,family,{scalarWidthBits:spec.scalarWidthBits,format:spec.format,unorderedFlagTuple:'ZF=PF=CF=1',destinationWrite:false},[...left.possibleFaults,...right.possibleFaults,fpFault(family,spec.signaling)],['flags','faults','other']);}

function liftPacked(ctx,family,encoding,spec){const width=encoding.kind==='vex'?encoding.vectorWidthBits:128;if(![128,256].includes(width))return ctx.partial('x86-fp-packed-width-unmodelled',['registers','memory','faults','other']);let d,a,b;if(encoding.kind==='legacy'){[d,b]=ctx.operands;a=d;}else[d,a,b]=ctx.operands;if(!isVector(d)||!isVector(a)||d.widthBits!==width||a.widthBits!==width)return ctx.partial(`x86-${family}-operand-shape-unmodelled`,['registers','memory','faults','other']);const left=readX86VectorOperand(ctx,a,width),right=readX86VectorOperand(ctx,b,width);if(!left||!right)return ctx.partial(`x86-${family}-source-unmodelled`,['registers','memory','faults','other']);const output=ctx.intrinsic('x86.fp.packed-arithmetic',[left.value,right.value],[width],{registersRead:unique([left.registerId,right.registerId]),registersWritten:[d.register.physicalId],determinism:'nondeterministic',symbolicDetail:'summary-only',metadata:{operation:spec.operation,format:spec.format,vectorWidthBits:width,elementWidthBits:spec.elementWidthBits,laneCount:width/spec.elementWidthBits,encodingKind:encoding.kind,fpEnvironmentDependency:'MXCSR',exactArchitecturalSummary:false}})[0];if(!writeX86VectorRegister(ctx,d,output,encoding,width))return ctx.partial(`x86-${family}-destination-unmodelled`,['registers','faults','other']);return fpPartial(ctx,family,{vectorWidthBits:width,elementWidthBits:spec.elementWidthBits,laneCount:width/spec.elementWidthBits,encodingKind:encoding.kind},[...left.possibleFaults,...right.possibleFaults,fpFault(family)]);}

function integerInput(ctx,operand){if(operand?.type==='register'&&operand.register?.kind!=='vector'){const value=ctx.readRegister(operand);return value?{value,registerId:operand.register.physicalId,possibleFaults:[]}:null;}if(operand?.type==='memory'){const address=foundationAddress(ctx,operand);if(!address)return{integrationRequired:true};return{value:ctx.readMemory(address.expression,operand.widthBits,{space:address.space,metadata:{...address.metadata,integerConversion:true}}),registerId:null,possibleFaults:x86MemoryFaults('read',operand.widthBits)};}return null;}

function liftConversion(ctx,family,encoding){
  const base=baseFamily(family);
  if(base==='cvttss2si'||base==='cvttsd2si'){const[d,s]=ctx.operands,sourceBits=base==='cvttss2si'?32:64;if(d?.type!=='register'||d.register?.kind==='vector'||![32,64].includes(d.widthBits))return ctx.partial(`x86-${family}-destination-unmodelled`,['registers','faults','other']);const input=readScalar(ctx,s,sourceBits);if(input?.integrationRequired)return integrationPartial(ctx,family,['memory','registers','faults','other']);if(!input)return ctx.partial(`x86-${family}-source-unmodelled`,['registers','memory','faults','other']);const result=ctx.intrinsic('x86.fp.float-to-integer-trunc',[input.value],[d.widthBits],{registersRead:unique([input.registerId]),registersWritten:[d.register.physicalId],determinism:'nondeterministic',symbolicDetail:'summary-only',metadata:{operation:base,sourceWidthBits:sourceBits,destinationWidthBits:d.widthBits,rounding:'truncate-toward-zero',fpEnvironmentDependency:'MXCSR.exception-mask-status/DAZ',exactArchitecturalSummary:false}})[0];if(!ctx.writeRegister(d,result))return ctx.partial(`x86-${family}-register-write-unmodelled`,['registers','faults','other']);return fpPartial(ctx,family,{sourceWidthBits:sourceBits,destinationWidthBits:d.widthBits,rounding:'truncate-toward-zero'},[...input.possibleFaults,fpFault(family)]);}
  let d,m,s;if(encoding.kind==='legacy'){[d,s]=ctx.operands;m=d;}else[d,m,s]=ctx.operands;if(!isVector(d)||!isVector(m))return ctx.partial(`x86-${family}-operand-shape-unmodelled`,['registers','memory','faults','other']);let input,inputWidth,toBits;if(base==='cvtsi2ss'||base==='cvtsi2sd'){input=integerInput(ctx,s);inputWidth=s?.widthBits;toBits=base.endsWith('ss')?32:64;}else{inputWidth=base==='cvtss2sd'?32:64;toBits=base==='cvtss2sd'?64:32;input=readScalar(ctx,s,inputWidth);}if(input?.integrationRequired)return integrationPartial(ctx,family,['memory','registers','faults','other']);if(!input||!inputWidth)return ctx.partial(`x86-${family}-source-unmodelled`,['registers','memory','faults','other']);const result=ctx.intrinsic('x86.fp.conversion',[input.value],[toBits],{registersRead:unique([input.registerId]),registersWritten:[d.register.physicalId],determinism:'nondeterministic',symbolicDetail:'summary-only',metadata:{operation:base,sourceWidthBits:inputWidth,destinationWidthBits:toBits,sourceKind:(base==='cvtsi2ss'||base==='cvtsi2sd')?'signed-integer':'ieee-float',destinationFormat:toBits===32?'binary32':'binary64',fpEnvironmentDependency:'MXCSR',exactArchitecturalSummary:false}})[0];if(!destinationShape(ctx,encoding,d,m,result,toBits,false))return ctx.partial(`x86-${family}-destination-unmodelled`,['registers','faults','other']);return fpPartial(ctx,family,{sourceWidthBits:inputWidth,destinationWidthBits:toBits,conversion:base,encodingKind:encoding.kind},[...input.possibleFaults,fpFault(family)]);
}

import { liftX86VectorGeneralEffects } from './vector-general.js';

export function liftX86FloatingPointEffects(instruction, context = {}) {
  const family = String(instruction?.instructionFamily || '').toLowerCase(), base = baseFamily(family);
  if (['andps', 'andpd', 'orps', 'orpd', 'xorps', 'xorpd', 'pand', 'por', 'pxor', 'movdqa', 'movdqu', 'movaps', 'movups', 'movapd', 'movupd'].includes(base)) return null;
  if (X87_FAMILIES.has(base)) {
    const ctx = createX86EffectContext(instruction, context);
    return ctx.partial('x86-x87-physical-and-environment-state-unmodelled', ['registers', 'flags', 'faults', 'other'], { metadata: { family: 'fp', operation: family, x87StateInvented: false, missingState: ['st0-st7-80bit', 'TOP', 'tag-word', 'control-word', 'status-word', 'last-instruction/data pointers'], sharedDependencyRequired: ['x86-x87-physical-state', 'x86-decoder-x87-register-normalization'], normalizerReachability: 'implicit/explicit ST register forms are rejected before this lifter by the current shared register contract' } });
  }
  const recognized = SCALAR_MOVES.has(base) || SCALAR_ARITHMETIC.has(base) || SCALAR_SQRT.has(base) || SCALAR_COMPARE.has(base) || PACKED_ARITHMETIC.has(base) || CONVERSIONS.has(base);
  if (!recognized) return liftX86VectorGeneralEffects(instruction, context, 'fp');
  const ctx = createX86EffectContext(instruction, context);
  if (base === 'movsd' && !ctx.operands.some(isVector)) return null;
  const check = validateEncoding(ctx, family, !PACKED_ARITHMETIC.has(base));
  if (check.error) return check.error;
  const encoding = check.encoding;
  if (SCALAR_MOVES.has(base)) return liftScalarMove(ctx, family, encoding, SCALAR_MOVES.get(base));
  if (SCALAR_ARITHMETIC.has(base)) return liftScalarArithmetic(ctx, family, encoding, SCALAR_ARITHMETIC.get(base));
  if (SCALAR_SQRT.has(base)) return liftScalarSqrt(ctx, family, encoding, SCALAR_SQRT.get(base));
  if (SCALAR_COMPARE.has(base)) return liftScalarCompare(ctx, family, SCALAR_COMPARE.get(base));
  if (PACKED_ARITHMETIC.has(base)) return liftPacked(ctx, family, encoding, PACKED_ARITHMETIC.get(base));
  if (CONVERSIONS.has(base)) return liftConversion(ctx, family, encoding);
  return liftX86VectorGeneralEffects(instruction, context, 'fp');
}
