import test from 'node:test';
import assert from 'node:assert/strict';
import { materializeX86Address,x86EffectiveAddressExpression } from '../../../../js/targets/architecture/x86_64/effects/addressing.js';
import { createX86DecodedInstruction } from '../../../../js/targets/architecture/x86_64/decoded-instruction.js';
import { decoded,evaluateMaterializedAddress,independentEffectiveAddress,mem } from './helpers.mjs';
function memoryOf(instruction){return instruction.detail.operands.find((operand)=>operand.type==='memory');}
for(const fixture of [{name:'base only',base:'rax',baseValue:0x1234n,displacement:0n},{name:'base + positive displacement',base:'rbx',baseValue:0x1000n,displacement:0x34n},{name:'base + negative displacement',base:'rbx',baseValue:0x1000n,displacement:-0x20n},{name:'base + index',base:'rax',baseValue:0x100n,index:'rcx',indexValue:0x20n,scale:1,displacement:0n}]) test(`address: ${fixture.name}`,()=>{const instruction=decoded({family:'mov',operands:[mem({...fixture,widthBits:64})]}),operand=memoryOf(instruction),actual=evaluateMaterializedAddress(materializeX86Address,instruction,operand,{[fixture.base]:fixture.baseValue,[fixture.index]:fixture.indexValue}),expected=independentEffectiveAddress({baseValue:fixture.baseValue,indexValue:fixture.indexValue,scale:fixture.scale??1,displacement:fixture.displacement});assert.equal(actual,expected);});
for(const scale of [1,2,4,8]) test(`address: SIB scale ${scale} remains semantic`,()=>{const instruction=decoded({family:'mov',operands:[mem({base:'rax',index:'rcx',scale,displacement:-0x10n,widthBits:64})]}),operand=memoryOf(instruction),result=x86EffectiveAddressExpression(instruction,operand);assert.equal(result.metadata.scale,scale);assert.equal(result.expression.scale,scale);assert.equal(result.expression.index.scale,scale);assert.equal(evaluateMaterializedAddress(materializeX86Address,instruction,operand,{rax:0x1000n,rcx:0x21n}),independentEffectiveAddress({baseValue:0x1000n,indexValue:0x21n,scale,displacement:-0x10n}));});
test('address: RIP relative uses actual instruction length',()=>{for(const length of [5,7,11]){const instruction=decoded({family:'mov',address:0x7fff00001000n,length,operands:[mem({base:'rip',displacement:-0x123n,widthBits:64})]}),operand=memoryOf(instruction),result=x86EffectiveAddressExpression(instruction,operand);assert.equal(result.metadata.ripRelative,true);assert.equal(result.metadata.instructionLength,length);assert.equal(result.expression.nextInstructionAddress,instruction.address+BigInt(length));assert.equal(evaluateMaterializedAddress(materializeX86Address,instruction,operand),independentEffectiveAddress({rip:true,instructionAddress:instruction.address,instructionLength:length,displacement:-0x123n}));}});
test('address: displacement-only is retained and exact',()=>{const instruction=decoded({family:'mov',operands:[mem({base:null,index:null,displacement:0x12345678n,widthBits:32})]}),operand=memoryOf(instruction),result=x86EffectiveAddressExpression(instruction,operand);assert.equal(result.metadata.base,null);assert.equal(result.metadata.index,null);assert.equal(result.metadata.displacement,0x12345678n);assert.equal(evaluateMaterializedAddress(materializeX86Address,instruction,operand),0x12345678n);});
for(const segment of ['fs','gs']) test(`address: ${segment.toUpperCase()} remains TLS`,()=>{const instruction=decoded({family:'mov',operands:[mem({base:'rax',segment,widthBits:64})]}),result=x86EffectiveAddressExpression(instruction,memoryOf(instruction));assert.equal(result.space,'tls');assert.equal(result.metadata.segment,segment);assert.equal(result.metadata.segmentBaseRule,'tls-segment-base-unknown');assert.equal(result.expression.segment,segment);});
test('address: legacy long-mode segment base is not invented',()=>{const instruction=decoded({family:'mov',operands:[mem({base:'rax',segment:'ds',widthBits:64})]}),result=x86EffectiveAddressExpression(instruction,memoryOf(instruction));assert.equal(result.space,'memory');assert.equal(result.metadata.segmentBaseRule,'ignored-base-in-long-mode');});
test('address: proven 32-bit address-size wraps then zero-extends',()=>{const instruction=decoded({family:'mov',addressSizeBits:32,operands:[mem({base:'eax',index:'ecx',scale:4,displacement:0x40n,widthBits:32,addressSizeBits:32})]}),operand=memoryOf(instruction),result=x86EffectiveAddressExpression(instruction,operand);assert.equal(result.metadata.addressSizeBits,32);assert.equal(result.expression.calculation.kind,'zero-extend');const actual=evaluateMaterializedAddress(materializeX86Address,instruction,operand,{eax:0xfffffff0n,ecx:8n});assert.equal(actual,independentEffectiveAddress({baseValue:0xfffffff0n,indexValue:8n,scale:4,displacement:0x40n,addressSizeBits:32}));assert.equal(actual,0x50n);});
test('address: EIP relative address-size override wraps at 32 bits then zero-extends',()=>{const instruction=decoded({family:'lea',address:0xfffffffcn,length:8,addressSizeBits:32,operands:[mem({base:'eip',displacement:0x20n,widthBits:32,addressSizeBits:32})]}),operand=memoryOf(instruction),result=x86EffectiveAddressExpression(instruction,operand);assert.equal(result.metadata.ripRelative,true);assert.equal(result.expression.nextInstructionAddress,4n);assert.equal(result.expression.base.widthBits,32);assert.equal(evaluateMaterializedAddress(materializeX86Address,instruction,operand),0x24n);});
test('address: unknown segment fails closed instead of becoming normal memory',()=>{const instruction=decoded({family:'mov',operands:[mem({base:'rax',segment:'mystery',widthBits:64})]});assert.equal(x86EffectiveAddressExpression(instruction,memoryOf(instruction)),null);});
test('address: unsupported long-mode address size fails closed',()=>{const instruction=decoded({family:'mov',addressSizeBits:16,operands:[mem({base:'ax',widthBits:16,addressSizeBits:16})]});assert.equal(x86EffectiveAddressExpression(instruction,memoryOf(instruction)),null);});
test('address: invalid SIB scale is rejected by structured decode contract',()=>{assert.throws(()=>createX86DecodedInstruction({instructionId:'bad-scale',instructionCode:1,instructionFamily:'mov',address:0x1000n,length:4,rawBytes:new Uint8Array(4),detailAvailable:true,detail:{operands:[mem({base:'rax',index:'rcx',scale:3,widthBits:64})],operandCount:1}}),/x86-decoded-instruction-invalid-memory-scale/);});
test('address: instruction provenance is embedded in structural address',()=>{const instruction=decoded({family:'mov',operands:[mem({base:'rax',displacement:8n,widthBits:64})]}),result=x86EffectiveAddressExpression(instruction,memoryOf(instruction));assert.equal(result.expression.originInstructionId,instruction.instructionId);assert.equal(result.metadata.originInstructionId,instruction.instructionId);});
test('address: vector index is accepted only for VSIB gather/scatter families',()=>{const malformed=decoded({family:'jmp',operands:[mem({base:'rax',index:'xmm0',scale:4,widthBits:64})]});assert.equal(x86EffectiveAddressExpression(malformed,memoryOf(malformed)),null);const gather=decoded({family:'vgatherdps',operands:[mem({base:'rax',index:'xmm0',scale:4,widthBits:64})]});const result=x86EffectiveAddressExpression(gather,memoryOf(gather));assert.ok(result);assert.equal(result.expression.index.kind,'vector-scaled-index');});
