import test from 'node:test';
import assert from 'node:assert/strict';
import { liftX86MachineEffects } from '../../../../js/targets/architecture/x86_64/effects/index.js';
import { decoded,imm,mem,operations,reg } from './helpers.mjs';
function lift(input){const instruction=decoded(input),bundle=liftX86MachineEffects(instruction);assert.ok(bundle,`expected MachineEffects for ${input.family}`);return{instruction,bundle};}
const reads=(bundle)=>operations(bundle,'memory-read'),writes=(bundle)=>operations(bundle,'memory-write');
for(const family of ['mov','movabs'])test(`${family}: memory load preserves exact width and little endian`,()=>{const{bundle}=lift({family,operands:[reg('rax',64,'write'),mem({base:'rbx',displacement:8n,widthBits:64,access:'read'})]});assert.equal(bundle.completeness,'exact');assert.equal(reads(bundle).length,1);assert.equal(writes(bundle).length,0);assert.equal(reads(bundle)[0].access.widthBits,64);assert.equal(reads(bundle)[0].access.endian,'little');assert.equal(operations(bundle,'register-write').at(-1).register.registerId,'rax');});
test('mov: register and immediate stores are explicit',()=>{for(const source of [reg('ecx',32,'read'),imm(0x12345678n,32,32)]){const{bundle}=lift({family:'mov',operands:[mem({base:'rax',widthBits:32,access:'write'}),source]});assert.equal(bundle.completeness,'exact');assert.equal(reads(bundle).length,0);assert.equal(writes(bundle).length,1);assert.equal(writes(bundle)[0].access.widthBits,32);assert.equal(writes(bundle)[0].access.endian,'little');}});
for(const[family,sourceBits,destination]of[['movzx',8,'eax'],['movsx',16,'rax'],['movsxd',32,'rax']])test(`${family}: memory extension uses memory width`,()=>{const destinationBits=destination==='eax'?32:64,{bundle}=lift({family,operands:[reg(destination,destinationBits,'write'),mem({base:'rdi',widthBits:sourceBits,access:'read'})]});assert.equal(reads(bundle)[0].access.widthBits,sourceBits);const extension=operations(bundle,'value').find((op)=>(op.opcode==='zext'||op.opcode==='sext')&&op.metadata.fromBits===sourceBits&&op.metadata.toBits===destinationBits);assert.ok(extension);assert.equal(extension.opcode,family==='movzx'?'zext':'sext');});
for(const family of ['add','sub','and','or','xor'])test(`${family}: memory destination is one same-address RMW`,()=>{const{bundle}=lift({family,operands:[mem({base:'rax',index:'rcx',scale:4,displacement:-16n,widthBits:64,access:'read-write'}),reg('rdx',64,'read')]});assert.equal(reads(bundle).length,1);assert.equal(writes(bundle).length,1);assert.deepEqual(reads(bundle)[0].access.addressExpr,writes(bundle)[0].access.addressExpr);assert.equal(reads(bundle)[0].metadata.rmwId,writes(bundle)[0].metadata.rmwId);assert.equal(bundle.metadata.sameCanonicalAddress,true);assert.equal(reads(bundle)[0].access.atomic,false);assert.equal(writes(bundle)[0].access.atomic,false);});
for(const family of ['add','sub','and','or','xor'])test(`${family}: memory source updates register only`,()=>{const{bundle}=lift({family,operands:[reg('rax',64,'read-write'),mem({base:'rbx',widthBits:64,access:'read'})]});assert.equal(reads(bundle).length,1);assert.equal(writes(bundle).length,0);assert.ok(operations(bundle,'register-write').some((op)=>op.register.registerId==='rax'));});
test('not: memory form is RMW without flag writes',()=>{const{bundle}=lift({family:'not',operands:[mem({base:'rax',widthBits:32,access:'read-write'})]});assert.equal(reads(bundle).length,1);assert.equal(writes(bundle).length,1);assert.deepEqual(reads(bundle)[0].access.addressExpr,writes(bundle)[0].access.addressExpr);assert.equal(operations(bundle,'flag-write').length,0);assert.equal(bundle.completeness,'exact');});
for(const family of ['cmp','test']){test(`${family}: memory destination is read-only`,()=>{const{bundle}=lift({family,operands:[mem({base:'rax',widthBits:32,access:'read'}),reg('ecx',32,'read')]});assert.equal(reads(bundle).length,1);assert.equal(writes(bundle).length,0);assert.equal(bundle.metadata.destinationWrite,false);assert.equal(bundle.metadata.memoryWrite,false);});test(`${family}: structured memory source direction is honored`,()=>{const{bundle}=lift({family,operands:[reg('eax',32,'read'),mem({base:'rbx',widthBits:32,access:'read'})]});assert.equal(reads(bundle).length,1);assert.equal(writes(bundle).length,0);});}
test('setcc: memory result is byte-wide',()=>{const{bundle}=lift({family:'sete',conditionCode:'e',operands:[mem({base:'rax',widthBits:8,access:'write'})]});assert.equal(writes(bundle).length,1);assert.equal(writes(bundle)[0].access.widthBits,8);assert.ok(operations(bundle,'flag-read').some((op)=>op.flag.flagId==='RFLAGS.ZF'));});
test('cmovcc: memory source read is unconditional',()=>{const{bundle}=lift({family:'cmovne',conditionCode:'ne',operands:[reg('rax',64,'write'),mem({base:'rbx',widthBits:64,access:'read'})]});assert.equal(reads(bundle).length,1);assert.equal(writes(bundle).length,0);assert.equal(bundle.metadata.sourceReadUnconditional,true);assert.equal(operations(bundle,'value').find((op)=>op.opcode==='select').metadata.memoryReadOccursRegardlessOfCondition,true);});
test('push: RSP decrement, stack write, RSP write',()=>{const{bundle}=lift({family:'push',length:1,bytes:[0x50],operands:[reg('rax',64,'read')],implicitReads:['rsp'],implicitWrites:['rsp']});assert.ok(operations(bundle,'register-read').some((op)=>op.register.registerId==='rsp'));assert.equal(writes(bundle).length,1);assert.equal(writes(bundle)[0].access.widthBits,64);assert.equal(bundle.metadata.stackDelta,-8);});
test('push: memory source precedes stack store',()=>{const{bundle}=lift({family:'push',operands:[mem({base:'rsp',displacement:16n,widthBits:64,access:'read'})]});assert.equal(reads(bundle).length,1);assert.equal(writes(bundle).length,1);assert.ok(bundle.possibleFaults.length>=2);assert.equal(reads(bundle)[0].metadata.sourceAddressBeforeStackUpdate,true);});
test('pop: normal register destination',()=>{const{bundle}=lift({family:'pop',length:1,bytes:[0x5b],operands:[reg('rbx',64,'write')],implicitReads:['rsp'],implicitWrites:['rsp']});assert.equal(reads(bundle).length,1);assert.equal(bundle.metadata.stackDelta,8);assert.ok(operations(bundle,'register-write').some((op)=>op.register.registerId==='rbx'));});
test('pop rsp: increment then destination overwrite',()=>{const{bundle}=lift({family:'pop',operands:[reg('rsp',64,'write')],implicitReads:['rsp'],implicitWrites:['rsp']});const r=operations(bundle,'register-write').filter((op)=>op.register.registerId==='rsp');assert.equal(r.length,2);assert.equal(bundle.metadata.rspDestination,true);assert.equal(bundle.metadata.sequencing,'increment-rsp-then-destination-overwrites-rsp');assert.deepEqual(r.at(-1).value,reads(bundle)[0].value);});
test('pop [rsp]: destination address after RSP increment',()=>{const{bundle}=lift({family:'pop',operands:[mem({base:'rsp',widthBits:64,access:'write'})],implicitReads:['rsp'],implicitWrites:['rsp']});assert.equal(reads(bundle).length,1);assert.equal(writes(bundle).length,1);assert.equal(writes(bundle)[0].metadata.destinationAddressAfterRspIncrement,true);assert.equal(writes(bundle)[0].access.addressExpr.kind,'temporary');});
test('unsupported 16-bit long-mode effective address becomes partial',()=>{const{bundle}=lift({family:'mov',addressSizeBits:16,operands:[reg('rax',64,'write'),mem({base:'ax',widthBits:64,addressSizeBits:16,access:'read'})]});assert.equal(bundle.completeness,'partial');assert.match(bundle.unknownEffects.reason,/address-unmodelled/);});
test('unknown segment never becomes ordinary memory',()=>{const{bundle}=lift({family:'mov',operands:[reg('rax',64,'write'),mem({base:'rbx',segment:'mystery',widthBits:64})]});assert.equal(bundle.completeness,'partial');assert.equal(reads(bundle).length,0);});
test('integrated ADC memory RMW consumes CF and preserves one address identity',()=>{const{bundle}=lift({family:'adc',operands:[mem({base:'rax',widthBits:64,access:'read-write'}),reg('rbx',64,'read')]});assert.equal(bundle.completeness,'exact-with-intrinsic');assert.equal(operations(bundle,'flag-read').filter((op)=>op.flag.flagId==='RFLAGS.CF').length,1);assert.equal(reads(bundle).length,1);assert.equal(writes(bundle).length,1);assert.equal(reads(bundle)[0].metadata.rmwId,writes(bundle)[0].metadata.rmwId);assert.deepEqual(reads(bundle)[0].access.addressExpr,writes(bundle)[0].access.addressExpr);});
test('memory faults retain canonical causes',()=>{const{bundle}=lift({family:'mov',operands:[reg('rax',64,'write'),mem({base:'rbx',widthBits:64})]});assert.deepEqual(bundle.possibleFaults.find((entry)=>entry.kind==='memory-access-fault').detail.causes,['segment','non-canonical-address','page','protection','alignment-check']);});
test('memory provenance survives instruction to access',()=>{const{instruction,bundle}=lift({family:'add',operands:[reg('rax',64,'read-write'),mem({base:'rbx',index:'rcx',scale:2,displacement:7n,widthBits:64})]});assert.ok(bundle.origin.instructionIds.includes(instruction.instructionId));for(const op of bundle.operations)assert.equal(op.metadata.originInstructionId,instruction.instructionId);assert.equal(reads(bundle)[0].access.addressExpr.originInstructionId,instruction.instructionId);});
test('formatted operand string is not semantic truth',()=>{const{bundle}=lift({family:'mov',operands:[reg('rax',64,'write'),mem({base:'rbx',displacement:4n,widthBits:64})],mnemonic:'garbage-display',opStr:'[totally fake + text*99]'});assert.equal(bundle.completeness,'exact');assert.equal(reads(bundle)[0].metadata.base,'rbx');assert.equal(String(reads(bundle)[0].metadata.displacement),'4');});
for(const family of ['pushf','pushfq','popf','popfq'])test(`${family}: flags stack transfer fails closed until architectural masks and faults are modeled`,()=>{const{bundle}=lift({family,operands:[]});assert.equal(bundle.completeness,'partial');assert.match(bundle.unknownEffects.reason,/architectural-flags-semantics-unmodelled/);assert.equal(bundle.metadata.failClosed,true);assert.equal(reads(bundle).length,0);assert.equal(writes(bundle).length,0);});
