import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import '../../../../js/targets/architecture/x86_64/capstone-structured.js';
import { createX86DecodedInstruction } from '../../../../js/targets/architecture/x86_64/decoded-instruction.js';
import { liftX86MachineEffects } from '../../../../js/targets/architecture/x86_64/effects/index.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../..'),capstoneModulePath=path.join(os.tmpdir(),`hex-p5-2-capstone-${process.pid}-${Date.now()}.cjs`),structured=globalThis.HexX86CapstoneStructured;
async function createDecoder(){assert.ok(structured);fs.copyFileSync(path.join(root,'capstone.js'),capstoneModulePath);const require=createRequire(import.meta.url),MCapstone=require(capstoneModulePath),M=await MCapstone({locateFile:(name)=>path.join(root,name),print:()=>{},printErr:()=>{}}),handlePointer=M._malloc(4),outputPointer=M._malloc(4);assert.equal(M.ccall('cs_open','number',['number','number','pointer'],[M.ARCH_X86,M.MODE_64|M.MODE_LITTLE_ENDIAN,handlePointer]),0);const handle=M.getValue(handlePointer,'i32');assert.equal(M.ccall('cs_option','number',['number','number','number'],[handle,M.OPT_DETAIL,M.OPT_ON]),0);async function decode(bytes,address=0x401000n){const input=Uint8Array.from(bytes),buffer=M._malloc(input.length);M.writeArrayToMemory(input,buffer);const count=M.ccall('cs_disasm','number',['number','number','number','number','number','number'],[handle,buffer,input.length,address,1,outputPointer]);assert.equal(count,1);const pointer=M.getValue(outputPointer,'i32');try{return structured.parseInstruction(M,handle,pointer,{address,mode:'long-64'});}finally{M.ccall('cs_free','void',['number','number'],[pointer,count]);M._free(buffer);}}function close(){try{M.ccall('cs_close','number',['pointer'],[handlePointer]);}catch{}M._free(outputPointer);M._free(handlePointer);fs.rmSync(capstoneModulePath,{force:true});}return{decode,close};}
const memOps=(bundle,kind)=>bundle.operations.filter((op)=>op.kind===kind);
let effectSequence=0;
function effects(decodedInstruction){effectSequence+=1;return liftX86MachineEffects(decodedInstruction,{instructionId:`p5-2:real-byte:${effectSequence}:${decodedInstruction.address.toString(16)}`});}
test('real-byte structured decoder -> P5-2 representative corpus',async()=>{const decoder=await createDecoder();try{const sib=await decoder.decode([0x48,0x8b,0x44,0x8b,0xf0],0x401000n);assert.equal(sib.length,5);assert.equal(sib.detail.operands[1].type,'memory');assert.equal(sib.detail.operands[1].memory.base,'rbx');assert.equal(sib.detail.operands[1].memory.index,'rcx');assert.equal(sib.detail.operands[1].memory.scale,4);assert.equal(sib.detail.operands[1].memory.displacement,-16n);assert.equal(sib.detail.operands[1].widthBits,64);assert.equal(memOps(effects(sib),'memory-read')[0].access.widthBits,64);
const rip=await decoder.decode([0x48,0x8b,0x05,0x78,0x56,0x34,0x12],0x402000n);assert.equal(rip.length,7);assert.equal(rip.detail.operands[1].memory.base,'rip');assert.equal(rip.detail.operands[1].memory.displacement,0x12345678n);const ripRead=memOps(effects(rip),'memory-read')[0];assert.equal(ripRead.access.addressExpr.ripRelative,true);assert.equal(String(ripRead.access.addressExpr.nextInstructionAddress),'4202503');
assert.equal(createX86DecodedInstruction(sib).detail.operands[1].memory.displacement,-16n);
const fsLoad=await decoder.decode([0x64,0x48,0x8b,0x00],0x403000n);assert.deepEqual([...fsLoad.detail.prefixes.legacy],[0x64]);assert.equal(fsLoad.detail.operands[1].memory.segment,'fs');assert.equal(memOps(effects(fsLoad),'memory-read')[0].access.space,'tls');
const movStore=await decoder.decode([0x48,0x89,0x08],0x404000n);assert.equal(movStore.detail.operands[0].type,'memory');assert.equal(movStore.detail.operands[0].widthBits,64);assert.equal(memOps(effects(movStore),'memory-write').length,1);
const push=await decoder.decode([0x50],0x405000n),pushN=createX86DecodedInstruction(push);assert.equal(pushN.length,1);assert.ok(pushN.detail.implicitReads.some((entry)=>entry.physicalId==='rsp'));assert.equal(memOps(effects(push),'memory-write').length,1);
const pop=await decoder.decode([0x58],0x405100n),popN=createX86DecodedInstruction(pop);assert.equal(popN.length,1);assert.ok(popN.detail.implicitWrites.some((entry)=>entry.physicalId==='rsp'));assert.equal(memOps(effects(pop),'memory-read').length,1);
const rep=await decoder.decode([0xf3,0xa4],0x406000n);assert.deepEqual([...rep.detail.prefixes.legacy],[0xf3]);const repBundle=effects(rep);assert.equal(repBundle.completeness,'exact-with-intrinsic');assert.equal(repBundle.metadata.repeatKind,'rep');assert.equal(repBundle.metadata.exactRepeatedSummary,true);assert.ok(repBundle.operations.length<20);
const xadd=await decoder.decode([0xf0,0x48,0x0f,0xc1,0x08],0x407000n);assert.deepEqual([...xadd.detail.prefixes.legacy],[0xf0]);assert.equal(xadd.detail.operands[0].type,'memory');assert.equal(xadd.detail.operands[0].widthBits,64);const xb=effects(xadd);assert.equal(memOps(xb,'memory-read')[0].access.atomic,true);assert.equal(memOps(xb,'memory-write')[0].access.atomic,true);
const xchg=await decoder.decode([0x48,0x87,0x08],0x408000n);assert.equal(xchg.detail.operands[0].type,'memory');const xg=effects(xchg);assert.equal(memOps(xg,'memory-read')[0].access.atomic,true);assert.equal(memOps(xg,'memory-write')[0].access.atomic,true);
const registerXchg=await decoder.decode([0x48,0x87,0xc8],0x408100n);assert.deepEqual(registerXchg.detail.operands.map((operand)=>operand.type),['register','register']);const registerXchgEffects=effects(registerXchg);assert.equal(registerXchgEffects.completeness,'exact');assert.equal(registerXchgEffects.metadata.registerExchange,true);assert.equal(registerXchgEffects.operations.filter((operation)=>operation.kind==='memory-read').length,0);assert.equal(registerXchgEffects.operations.filter((operation)=>operation.kind==='register-write').length,2);
const cmpxchg=await decoder.decode([0x48,0x0f,0xb1,0x08],0x409000n);assert.equal(cmpxchg.detail.operands[0].type,'memory');const cb=effects(cmpxchg);assert.equal(cb.completeness,'exact-with-intrinsic');assert.equal(cb.unknownEffects,undefined);assert.equal(cb.metadata.conditional,true);assert.equal(cb.metadata.implicitAccumulator,'rax');const cmpxchgWrite=memOps(cb,'memory-write')[0];assert.equal(cmpxchgWrite.metadata.conditionalValue,true);assert.equal(cmpxchgWrite.metadata.failurePathArchitecturalWrite,true);assert.equal(cmpxchgWrite.metadata.failurePathWritesOldDestination,true);assert.equal(cmpxchgWrite.metadata.architecturalWriteCycleRegardlessOfComparison,true);}finally{decoder.close();}});
