import test from 'node:test';import assert from 'node:assert/strict';import{spawnSync}from'node:child_process';import{mkdtempSync,writeFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import {SCALAR_LOOP_SCHEMA,LOOP_OBSERVABLE_CONTRACT} from '../../js/core/evidence/loop-invariant.js';
import {synthesizeScalarLoopInvariant} from '../../js/core/evidence/loop-synthesis.js';
import {replayPortableChecks} from '../../js/core/evidence/portable-replay.js';
import {queryLoopInvariant} from '../../js/analysis/query/semantic/loop-evidence.js';
import {fixture,workFor} from './helpers.mjs';
const iv=(lo,hi=lo)=>({lower:String(lo),upper:String(hi)});
const model=()=>({schema:SCALAR_LOOP_SCHEMA,bits:8,entry:iv(0),guard:iv(0,9),step:'1',observableContract:LOOP_OBSERVABLE_CONTRACT});
for(const [label,change,post,expected]of[['ascending',()=>{},iv(10),'candidate-checked'],['descending',m=>{m.entry=iv(10);m.guard=iv(1,10);m.step='-1'},iv(0),'candidate-checked'],['skipping',m=>m.step='2',iv(10,11),'candidate-checked'],['false postcondition',()=>{},iv(9),'unknown'],['zero iterations',m=>m.entry=iv(12),iv(12),'candidate-checked'],['full modular cycle',m=>{m.entry=iv(250);m.guard=iv(0,255);m.step='10'},iv(0,255),'candidate-checked']])test('synthesis '+label,t=>{const m=model();change(m);const r=synthesizeScalarLoopInvariant(m,post,{work:workFor(t)});assert.equal(r.status,expected);assert.ok(r.attempts.length<=3);assert.equal(r.semanticProof,false);});
function context(f){return{isCurrent:()=>true,model:model(),binding:{worldId:f.world.id,assumptionsId:f.assumptions.id,snapshotId:'snap',functionLocator:'f',loopId:'l',modelRevision:'v1',artifactId:'a',sourceReferences:['header']}};}
const q=()=>({functionId:'f',loopId:'l',synthesize:true,postcondition:iv(10)});
const options=(t,f,c)=>({...f,work:workFor(t),snapshotId:'snap',getContext:async()=>c,isCurrent:()=>true});
test('synthesis and detached replay use the same independent checker',async t=>{const f=fixture(),c=context(f),r=await queryLoopInvariant(q(),options(t,f,c));assert.equal(r.checked.status,'verified-model');const replay=await replayPortableChecks(r.capsule,{work:workFor(t)});assert.equal(replay.allListedDerivationsChecked,true);assert.equal(replay.sourceBinding,'detached-unverified');assert.equal((await queryLoopInvariant({...q(),capsule:r.capsule},options(t,f,c))).capsuleRebound,true);});
test('live rebind rejects changed model even at same external revision string',async t=>{const f=fixture(),c=context(f),r=await queryLoopInvariant(q(),options(t,f,c));c.model.entry=iv(1);assert.equal((await queryLoopInvariant({...q(),capsule:r.capsule},options(t,f,c))).status,'rejected');});
test('version mismatch is UNKNOWN and postcondition tamper rejected by checker',async t=>{const f=fixture(),r=await queryLoopInvariant(q(),options(t,f,context(f))),copy=structuredClone(r.capsule);copy.checkerVersion='future';assert.equal((await replayPortableChecks(copy,{work:workFor(t)})).counts.unknown,1);copy.checkerVersion=r.capsule.checkerVersion;copy.candidate.postcondition=iv(9);assert.equal((await replayPortableChecks(copy,{work:workFor(t)})).counts.rejected,1);});
test('portable CLI accepts actual exported loop capsule without a provider',async t=>{const f=fixture(),r=await queryLoopInvariant(q(),options(t,f,context(f))),dir=mkdtempSync(join(tmpdir(),'scpa-loop-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const p=join(dir,'capsule.json');writeFileSync(p,JSON.stringify(r.capsule));const result=spawnSync(process.execPath,['tools/portable-checker/check.mjs',p],{timeout:10000,encoding:'utf8',maxBuffer:65536});assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).semanticProof,false);});
test('synthesis never allows simultaneous user supplied invariant',async t=>{const f=fixture();await assert.rejects(queryLoopInvariant({...q(),invariant:iv(0,10)},options(t,f,context(f))),/invariant-conflict/);});
