import {createReadabilityTaskPlan,auditReadabilityTaskRecords} from '../../js/analysis/benchmark/task-readability.js';
import test from'node:test';import assert from'node:assert/strict';
import{expr}from'../../js/decompiler/ast/nodes.js';
import{proposeMaskCondition,lowerMaskCondition,projectTaskIdiomView}from'../../js/core/evidence/task-idiom.js';
import{checkBitvectorViewRelation}from'../../js/core/evidence/bv-view-proof.js';
import{beginScopedTransformCapture,finishScopedTransformCapture}from'../../js/decompiler/phase8/scoped-transform-capture.js';
import{fixture,workFor}from'./helpers.mjs';import{nativeWorkerFixture}from'./native-worker-fixture.mjs';
const variable=()=>expr.variable('flags',32,false,null,{ssaId:1});
const condition=(op='!=',swap=false)=>{const mask=expr.constant(0x12n,32,false),and=expr.binary('and',swap?mask:variable(),swap?variable():mask,32,false);return expr.compare(op,and,expr.constant(0n,32,false),false);};
for(const op of ['==','!='])for(const swap of [false,true])test('task idiom '+op+' swap='+swap,()=>{const c=condition(op,swap),p=proposeMaskCondition(c);assert.equal(p.maskHex,'0x12');assert.equal(checkBitvectorViewRelation(c,lowerMaskCondition(p)).status,'verified');const bad={...p,maskHex:'0x13'};assert.notEqual(checkBitvectorViewRelation(c,lowerMaskCondition(bad)).status,'verified');});
function view(f){const expression=condition();const raw={semanticAst:{conditions:[]},lines:[{text:'if ((flags & 0x12) != 0)'}],cAst:{body:[{kind:'if',text:'if ((flags & 0x12) != 0)',source:{rows:[0]},semantic:{op:'condition',expression}}]}};
 const capture=finishScopedTransformCapture(beginScopedTransformCapture(raw,true),raw),slot=capture.finalExpressionStatements[0];
 return{schema:'scoped-local-owner-projection/v1',kind:'transforms',version:'1.0.0',status:'completed',worldId:f.world.id,assumptionsId:f.assumptions.id,snapshotId:'snap',functionId:'f',binaryId:'binary-scpa-test',producerArtifactId:'artifact',capture,finalStatements:[{index:0,text:slot.text,statementKind:slot.statementKind,source:slot.source,location:slot.location}],remaining:[],sourceBinding:'fixture'};}
const opts=(t,f)=>({...f,snapshotId:'snap',functionId:'f',producerArtifactId:'artifact',isCurrent:()=>true,work:workFor(t)});
test('unchanged native expressions are captured for task gate without a fake transformation receipt',async t=>{const f=fixture(),v=view(f);assert.equal(v.capture.relations.length,0);const r=await projectTaskIdiomView(v,{task:'inspect-bit-condition'},opts(t,f));assert.equal(r.changedViewCount,1);assert.equal(r.statements[0].selection,'checked-idiom');assert.equal(r.humanTaskResults,'UNMEASURED');assert.equal(r.rewriteAuthorized,false);assert.match(r.statements[0].originalText,/flags/);});
test('unrelated task keeps every original statement and order',async t=>{const f=fixture(),v=view(f),r=await projectTaskIdiomView(v,{task:'trace-value'},opts(t,f));assert.equal(r.changedViewCount,0);assert.equal(r.statements.length,v.finalStatements.length);assert.equal(r.statements[0].display,r.statements[0].originalText);});
for(const key of ['text','source','location','index'])test('bind actual final slot '+key,async t=>{const f=fixture(),v=structuredClone(view(f));v.finalStatements[0][key]=key==='index'?4:'different';await assert.rejects(projectTaskIdiomView(v,{task:'inspect-bit-condition'},opts(t,f)),/task-final-statement-binding/);});
test('selected IDs outside scope cannot silently produce empty task',async t=>{const f=fixture();await assert.rejects(projectTaskIdiomView(view(f),{task:'inspect-bit-condition',statementIds:['missing']},opts(t,f)),/outside-capture/);});
test('loads and noninteger predicates do not become pure mask idioms',()=>{const c=condition();c.left.left=expr.load({key:'p'},32,null,{volatile:true});c.effect='volatile';assert.equal(proposeMaskCondition(c),null);assert.equal(proposeMaskCondition(expr.compare('==',expr.floatConstant(0),expr.floatConstant(0))),null);});
test('actual native worker path supplies task view without canonical rewrite',async t=>{const f=await nativeWorkerFixture(t,{rowsByLocator:{'0x1000':[['uxtb','w0, w0',0x53001c00],['ret','',0xd65f03c0]]}});const r=await f.invoke('taskIdiomView',{functionId:'0x1000',task:'trace-value'});assert.equal(r.status,'completed');assert.ok(r.statements.length);assert.equal(r.rewriteAuthorized,false);assert.equal(r.humanTaskResults,'UNMEASURED');});

test('counterbalanced fixed task denominator keeps missing and failed records',async t=>{const f=fixture(),v=await projectTaskIdiomView(view(f),{task:'inspect-bit-condition'},opts(t,f));const plan=createReadabilityTaskPlan(v,['person-a','person-b'],{work:workFor(t)});assert.equal(plan.expected,4);assert.deepEqual(plan.rows.map(r=>r.variant),['original','idiom','idiom','original']);let result=auditReadabilityTaskRecords(plan,[],{work:workFor(t)});assert.equal(result.missing,4);assert.equal(result.improvementClaim,false);
const records=plan.rows.map((r,i)=>({trialId:r.id,sourceViewId:plan.sourceViewId,outcome:'completed',durationMs:100+i,answer:r.expectedAnswer,evidenceIds:['record-'+i]}));records[1].answer='0x13';result=auditReadabilityTaskRecords(plan,records,{work:workFor(t)});assert.equal(result.incorrect,1);assert.equal(result.pairs[0].durationDeltaMs,null);assert.equal(result.humanStudyQualified,false);assert.equal(result.pairs[1].durationDeltaMs,-1);
assert.throws(()=>auditReadabilityTaskRecords(plan,[records[0],records[0]],{work:workFor(t)}),/record-binding/);
assert.throws(()=>createReadabilityTaskPlan(structuredClone(v),['person-a'],{work:workFor(t)}),/issued-task-view/);
});
