export const CIL_METADATA_BUDGET_VERSION='hex-cil-metadata-budget-v1';
export const DEFAULT_CIL_METADATA_LIMITS=Object.freeze({maxRows:200000,maxObjects:1000000,maxStringBytes:8*1024*1024,maxOperations:8000000,maxElapsedMs:10000});
export class CilMetadataResourceLimitError extends Error{constructor(code,resource,used,limit){super(`${code} (${resource}: ${used} > ${limit})`);this.name='CilMetadataResourceLimitError';this.code=code;this.resource=resource;this.used=used;this.limit=limit;this.resourceLimited=true;this.cancelled=false;}}
export class CilMetadataCancelledError extends Error{constructor(signal){super('cil-metadata-cancelled');this.name='AbortError';this.code='cil-metadata-cancelled';this.resourceLimited=true;this.cancelled=true;this.cause=signal?.reason??null;}}
function limitValue(options,key){const raw=options[key]===undefined?DEFAULT_CIL_METADATA_LIMITS[key]:options[key];if(raw===null)return null;if(typeof raw!=='number'||!Number.isSafeInteger(raw)||raw<0)throw new TypeError(`cil-metadata-budget-limit-invalid:${key}`);return raw}
export function createCilMetadataAdmission(options={}){const limits=Object.freeze({maxRows:limitValue(options,'maxRows'),maxObjects:limitValue(options,'maxObjects'),maxStringBytes:limitValue(options,'maxStringBytes'),maxOperations:limitValue(options,'maxOperations'),maxElapsedMs:limitValue(options,'maxElapsedMs')}),signal=options.signal===undefined?null:options.signal;if(signal!=null&&typeof signal.aborted!=='boolean')throw new TypeError('cil-metadata-budget-signal-invalid');const now=options.monotonicNow===undefined?(()=>globalThis.performance?.now?.()??Date.now()):options.monotonicNow;if(typeof now!=='function')throw new TypeError('cil-metadata-budget-clock-invalid');const started=limits.maxElapsedMs==null?null:now(),usage={rows:0,objects:0,stringBytes:0,operations:0};let ticks=0;const charge=(field,resource,limit,code,amount)=>{if(signal?.aborted)throw new CilMetadataCancelledError(signal);if(typeof amount!=='number'||!Number.isSafeInteger(amount)||amount<0)throw new TypeError(`cil-metadata-budget-charge-invalid:${resource}`);const next=usage[field]+amount;usage[field]=next;if(limit!=null&&next>limit)throw new CilMetadataResourceLimitError(code,resource,next,limit);if(limits.maxElapsedMs!=null&&++ticks>=1024){ticks=0;if(now()-started>limits.maxElapsedMs)throw new CilMetadataResourceLimitError('cil-metadata-resource-limit-elapsed','elapsedMs',now()-started,limits.maxElapsedMs)}return next};return Object.freeze({version:CIL_METADATA_BUDGET_VERSION,limits,chargeRows:(n,t='aggregate')=>charge('rows',`rows:${t}`,limits.maxRows,'cil-metadata-resource-limit-rows',n),chargeObjects:n=>charge('objects','objects',limits.maxObjects,'cil-metadata-resource-limit-objects',n),chargeStringBytes:n=>charge('stringBytes','stringBytes',limits.maxStringBytes,'cil-metadata-resource-limit-string-bytes',n),chargeOperations:(n=1)=>charge('operations','operations',limits.maxOperations,'cil-metadata-resource-limit-operations',n),usage:()=>Object.freeze({...usage}),snapshot:()=>Object.freeze({version:CIL_METADATA_BUDGET_VERSION,limits,usage:Object.freeze({...usage})})})}
export function admitCilMetadataTables(admission,layout){if(!admission||!layout?.rowCounts)return 0;let total=0;for(const count of layout.rowCounts)total+=count;if(!Number.isSafeInteger(total))throw new TypeError('cil-metadata-budget-charge-invalid:rows');admission.chargeRows(total,'tables');return total}
export function isCilMetadataResourceLimit(error){return error?.resourceLimited===true}
export function isCilMetadataBudgetConfigError(error){return typeof error?.message==='string'&&error.message.startsWith('cil-metadata-budget-')}
