import { decodeDexInstructionBoundary } from './instruction-boundary.js';
const PREDICATES=Object.freeze({0x32:['if-eq','eq'],0x33:['if-ne','ne'],0x34:['if-lt','lt'],0x35:['if-ge','ge'],0x36:['if-gt','gt'],0x37:['if-le','le'],0x38:['if-eqz','eq'],0x39:['if-nez','ne'],0x3a:['if-ltz','lt'],0x3b:['if-gez','ge'],0x3c:['if-gtz','gt'],0x3d:['if-lez','le']});
function target(targetPc,index,insnsSize){if(!Number.isSafeInteger(targetPc)||targetPc<0||targetPc>=insnsSize)return{reason:'dex-branch-target-out-of-range'};const targetOffset=targetPc*2;if(index.instructionOffsets.has(targetOffset))return{targetOffset};return{reason:index.scanComplete?'dex-branch-target-not-instruction-boundary':'dex-control-flow-boundary-authority-incomplete'}}
function failFlow(mnemonic,locationReads,reason){return{mnemonic,locationReads,controlEffects:[],controlEntries:[],reason}}
export function buildDexControlFlowIndex(view,insnsStart,insnsSize){const instructionOffsets=new Set(),payloads=new Map();let at=0,scanComplete=true;while(at<insnsSize){const b=decodeDexInstructionBoundary(view,insnsStart,at,insnsSize),off=at*2;if(b.kind==='instruction')instructionOffsets.add(off);else if(b.kind==='payload')payloads.set(off,{signature:b.signature,length:b.length,mnemonic:b.mnemonic});else scanComplete=false;at+=b.length;if(b.stop)break}if(at!==insnsSize)scanComplete=false;return Object.freeze({instructionOffsets,payloads,scanComplete})}
function direct(view,start,size,pc,op,fmt,index){let mnemonic,disp;if(op===0x28){mnemonic='goto';disp=fmt>=0x80?fmt-0x100:fmt}else if(op===0x29){mnemonic='goto/16';disp=view.getInt16(start+(pc+1)*2,true)}else{mnemonic='goto/32';disp=view.getInt32(start+(pc+1)*2,true)}const t=target(pc+disp,index,size);if(t.reason)return failFlow(mnemonic,[],t.reason);return{mnemonic,locationReads:[],controlEffects:[{kind:'branch',targetOffset:t.targetOffset}],controlEntries:[t.targetOffset],reason:null}}
function conditional(view,start,size,pc,op,fmt,index){const [mnemonic,predicate]=PREDICATES[op],arity=op<=0x37?2:1,t=target(pc+view.getInt16(start+(pc+1)*2,true),index,size),f=target(pc+2,index,size),reads=arity===2?[{kind:'register',index:fmt&15,bits:32},{kind:'register',index:fmt>>>4,bits:32}]:[{kind:'register',index:fmt,bits:32}];if(t.reason)return failFlow(mnemonic,reads,t.reason);if(f.reason)return failFlow(mnemonic,reads,f.reason);return{mnemonic,locationReads:reads,controlEffects:[{kind:'conditional-branch',targetOffset:t.targetOffset,falseTargetOffset:f.targetOffset,condition:{kind:'integer-comparison',predicate,signed:true,arity,compareToZero:arity===1,widthBits:32}}],controlEntries:[t.targetOffset],reason:null}}
function sw(view,start,size,pc,op,fmt,index){const packed=op===0x2b,mnemonic=packed?'packed-switch':'sparse-switch',reads=[{kind:'register',index:fmt,bits:32}],payloadPc=pc+view.getInt32(start+(pc+1)*2,true);if(!Number.isSafeInteger(payloadPc)||payloadPc<0||payloadPc>=size)return failFlow(mnemonic,reads,'dex-switch-payload-out-of-range');if((payloadPc&1)!==0)return failFlow(mnemonic,reads,'dex-switch-payload-misaligned');const payloadOffset=payloadPc*2,payload=index.payloads.get(payloadOffset);if(!payload)return failFlow(mnemonic,reads,index.scanComplete?'dex-switch-payload-not-data-boundary':'dex-control-flow-boundary-authority-incomplete');if(payload.signature!==(packed?1:2))return failFlow(mnemonic,reads,'dex-switch-payload-kind-mismatch');const p=start+payloadOffset,n=view.getUint16(p+2,true),keys=[],disps=[];if(packed){const first=view.getInt32(p+4,true);for(let i=0;i<n;i++){const key=first+i;if(key< -0x80000000||key>0x7fffffff)return failFlow(mnemonic,reads,'dex-packed-switch-key-overflow');keys.push(key);disps.push(view.getInt32(p+8+i*4,true))}}else{let prev=null;for(let i=0;i<n;i++){const key=view.getInt32(p+4+i*4,true);if(prev!=null&&key<=prev)return failFlow(mnemonic,reads,'dex-sparse-switch-keys-not-strictly-increasing');keys.push(key);prev=key}const tb=p+4+n*4;for(let i=0;i<n;i++)disps.push(view.getInt32(tb+i*4,true))}const targets=[];for(const d of disps){const t=target(pc+d,index,size);if(t.reason)return failFlow(mnemonic,reads,t.reason);targets.push(t.targetOffset)}const def=target(pc+3,index,size);if(def.reason)return failFlow(mnemonic,reads,def.reason);return{mnemonic,locationReads:reads,controlEffects:[{kind:'switch',targetOffsets:targets,defaultTargetOffset:def.targetOffset,caseValues:keys,payloadOffset,payloadKind:packed?'packed':'sparse'}],controlEntries:[...targets],reason:null}}
export function decodeDexControlFlow({view,insnsStart,insnsSize,pc,opcode,formatByte,index}){if(opcode>=0x28&&opcode<=0x2a)return direct(view,insnsStart,insnsSize,pc,opcode,formatByte,index);if(opcode===0x2b||opcode===0x2c)return sw(view,insnsStart,insnsSize,pc,opcode,formatByte,index);if(opcode>=0x32&&opcode<=0x3d)return conditional(view,insnsStart,insnsSize,pc,opcode,formatByte,index);return null}
