import { liftDexMethod as liftBase } from './lifter-base.js';
import { dexTypeInfo } from './descriptor.js';
import { dexFieldEffects } from './field-effects.js';
import { decodeDexExceptionTable } from './exception-table.js';
import { dexDefinitionCodeError, dexMethodDefinitions } from './method-definitions.js';
import { decodeDexInstructionBoundary } from './instruction-boundary.js';
import { createManagedMethodId, createVMOperationId } from '../shared/identity.js';
import { createVMEffectBundle, createVMEffectFunction } from '../shared/vm-effects.js';

function unavailable(methodIdx,image,reason,options){
 const method=image?.methods?.[methodIdx],methodId=createManagedMethodId(image.moduleId,methodIdx,method?.name??`m_${methodIdx}`);
 const bundle=createVMEffectBundle({frontendId:'dex',methodId,operationId:createVMOperationId(methodId,0),bytecodeOffset:0,mnemonic:'unavailable_method',completeness:'unknown',unknownEffects:[{category:'calls',reason}]},options);
 return createVMEffectFunction({methodId,profileId:image.vmSpecEdition,frontendId:'dex',bundles:[bundle]},options);
}
function partial(bundle,reason){return {...bundle,consumedValues:[],producedValues:[],locationReads:[],locationWrites:[],memoryEffects:[],callEffects:[],controlEffects:[],completeness:'partial',unknownEffects:[{category:'other',reason}]}}
function rebuild(base,bundles,exceptionRegions,options){return createVMEffectFunction({methodId:base.methodId,profileId:base.profileId,frontendId:base.frontendId,entryState:base.entryState,bundles,exceptionRegions,validationReportId:base.validationReportId,resolutionCompleteness:base.resolutionCompleteness,origin:base.origin,metadata:base.metadata},options)}
export function liftDexMethod(methodIdx,image,options={}){
 const method=image?.methods?.[methodIdx];if(!method)return unavailable(methodIdx,image,'dex-method-id-missing',options);
 let definition;try{definition=dexMethodDefinitions(image).get(methodIdx)}catch(error){return unavailable(methodIdx,image,error?.message??'dex-invalid-method-definition',options)}
 const definitionError=definition?dexDefinitionCodeError(definition):'dex-method-definition-missing';if(definitionError)return unavailable(methodIdx,image,definitionError,options);
 const base=liftBase(methodIdx,image,options);if(!definition.codeOff)return base;
 const raw=image.rawBytes;if(!(raw instanceof Uint8Array))return unavailable(methodIdx,image,'dex-raw-bytes-required',options);
 const view=new DataView(raw.buffer,raw.byteOffset,raw.byteLength),codeOff=definition.codeOff;if(codeOff+16>raw.length)return unavailable(methodIdx,image,'dex-truncated-code-item',options);
 const registersSize=view.getUint16(codeOff,true),outsSize=view.getUint16(codeOff+4,true),triesSize=view.getUint16(codeOff+6,true),insnsSize=view.getUint32(codeOff+12,true),insnsStart=codeOff+16;
 if(insnsStart+insnsSize*2>raw.length)return unavailable(methodIdx,image,'dex-truncated-instructions',options);
 const boundaries=new Set(),controlEntries=new Set();
 for(let at=0;at<insnsSize;){let bd;try{bd=decodeDexInstructionBoundary(view,insnsStart,at,insnsSize)}catch(error){return unavailable(methodIdx,image,error?.message??'dex-invalid-instruction-boundary',options)}if(bd.kind==='instruction'){boundaries.add(at*2);const op=bd.opcode,word=view.getUint16(insnsStart+at*2,true),fmt=word>>>8;if(op===0x28)controlEntries.add((at+(fmt>=128?fmt-256:fmt))*2);else if(op===0x29||(op>=0x32&&op<=0x3d))controlEntries.add((at+view.getInt16(insnsStart+(at+1)*2,true))*2);else if(op===0x2a)controlEntries.add((at+view.getInt32(insnsStart+(at+1)*2,true))*2)}at+=bd.length;if(bd.stop)break}
 let exceptionRegions=[],handlerOffsets=new Set(),exceptionFailure=null;try{const ex=decodeDexExceptionTable(raw,{methodId:base.methodId,insnsStart,insnsSize,triesSize,types:image.types,boundaries});exceptionRegions=ex.regions;handlerOffsets=ex.handlerOffsets}catch(error){exceptionFailure=error?.message??'dex-invalid-exception-table'}
 let pendingResult=null;const bundles=[];
 for(const original of base.bundles){let b={...original},failure=registersSize<view.getUint16(codeOff+2,true)?'dex-register-file-size-invalid':null,nextResult=null;const byteOff=b.bytecodeOffset,pc=byteOff/2,word=view.getUint16(insnsStart+byteOff,true),op=word&255,fmt=word>>>8;let bd;try{bd=decodeDexInstructionBoundary(view,insnsStart,pc,insnsSize)}catch(error){bundles.push(partial(b,error?.message??'dex-invalid-instruction-boundary'));pendingResult=null;continue}const len=bd.length;
  /* The base lift already resolved this unit's boundary: a payload or an
     instruction truncated against insns_size arrives here as `partial` with
     its reason attached. Re-decoding it below would read operand words from
     beyond the declared instruction stream (padding/tries/foreign data) and
     re-publish them as `exact` effects (#5389). Only a real instruction may
     be enhanced. */
  if(bd.kind!=='instruction'){bundles.push(b);pendingResult=null;continue}
  if(op>=0x01&&op<=0x09){const family=Math.floor((op-1)/3),form=(op-1)%3,wide=family===1,obj=family===2,bits=wide?64:32,type=obj?{kind:'address',widthBits:32,addressSpace:'managed-heap'}:{kind:'bitvector',widthBits:bits};let dst,src,suffix='';if(form===0){dst=fmt&15;src=fmt>>>4}else if(form===1){dst=fmt;src=view.getUint16(insnsStart+(pc+1)*2,true);suffix='/from16'}else{if(fmt!==0)failure='dex-invalid-move16-reserved-bits';dst=view.getUint16(insnsStart+(pc+1)*2,true);src=view.getUint16(insnsStart+(pc+2)*2,true);suffix='/16'}const baseName=wide?'move-wide':obj?'move-object':'move';b={...b,mnemonic:baseName+suffix,locationReads:[{kind:'register',index:src,bits,type}],locationWrites:[{kind:'register',index:dst,bits,type}],producedValues:[],consumedValues:[],memoryEffects:[],callEffects:[],controlEffects:[],completeness:'exact',unknownEffects:[]};}
  else if(op>=0x0a&&op<=0x0d){const exception=op===0x0d,expected=op===0x0b?'wide':op===0x0c?'object':'single',info=exception?dexTypeInfo('Ljava/lang/Throwable;'):pendingResult;b={...b,mnemonic:exception?'move-exception':op===0x0b?'move-result-wide':op===0x0c?'move-result-object':'move-result'};if(exception&&(!handlerOffsets.has(byteOff)||controlEntries.has(byteOff)))failure='dex-move-exception-not-handler-entry';else if(!exception&&(!info||info.nextOffset!==byteOff||controlEntries.has(byteOff)||handlerOffsets.has(byteOff)))failure='dex-move-result-without-producer';else if(!exception&&info.category!==expected)failure='dex-move-result-category-mismatch';if(!failure)b={...b,locationReads:[{kind:'runtime',name:exception?`exception:${byteOff}`:'result',bits:info.bits,type:info.type}],locationWrites:[{kind:'register',index:fmt,bits:info.bits,type:info.type}],producedValues:[],consumedValues:[],memoryEffects:[],callEffects:[],controlEffects:[],completeness:'exact',unknownEffects:[]};}
  else if(op===0x1a){const idx=view.getUint16(insnsStart+(pc+1)*2,true);if(idx>= (image.strings?.length??0))failure='dex-reference-index-out-of-range';else b={...b,locationWrites:[{kind:'register',index:fmt,bits:32,type:dexTypeInfo('Ljava/lang/String;').type}],producedValues:[{bits:32,type:dexTypeInfo('Ljava/lang/String;').type,stringRef:image.strings[idx]}],completeness:'exact',unknownEffects:[]};}
  else if(op===0x22){const idx=view.getUint16(insnsStart+(pc+1)*2,true),desc=image.types?.[idx];if(desc==null)failure='dex-reference-index-out-of-range';else try{const info=dexTypeInfo(desc);if(info.category!=='object'||desc[0]!=='L')failure='dex-new-instance-class-required';else b={...b,locationWrites:[{kind:'register',index:fmt,bits:32,type:info.type}],producedValues:[{bits:32,type:info.type,classType:desc}],completeness:'exact',unknownEffects:[]}}catch{failure='dex-new-instance-class-required'}}
  else if(op>=0x52&&op<=0x6d){try{const fx=dexFieldEffects({opcode:op,formatByte:fmt,fieldIndex:view.getUint16(insnsStart+(pc+1)*2,true),image});b={...b,...fx,consumedValues:[],callEffects:[],controlEffects:[],completeness:'exact',unknownEffects:[]}}catch(error){failure=error?.message??'dex-invalid-field-effect'}}
  else if(op>=0x6e&&op<=0x72){const count=(fmt>>>4)&15,packed=view.getUint16(insnsStart+(pc+2)*2,true),idx=view.getUint16(insnsStart+(pc+1)*2,true),regs=[packed&15,(packed>>>4)&15,(packed>>>8)&15,(packed>>>12)&15,fmt&15].slice(0,Math.min(count,5)),target=image.methods?.[idx];if(!target)failure='dex-reference-index-out-of-range';else try{const params=(target.proto?.params??[]).map(t=>dexTypeInfo(t)),isStatic=op===0x71,expected=params.reduce((s,p)=>s+p.words,isStatic?0:1);if(count>5||count>outsSize||count!==expected)throw new TypeError('dex-invoke-argument-count-invalid');const reads=[];let at=0;if(!isStatic)reads.push({kind:'register',index:regs[at++],bits:32,type:dexTypeInfo('Ljava/lang/Object;').type});for(const p of params){if(p.words===2&&regs[at+1]!==regs[at]+1)throw new TypeError('dex-invoke-wide-argument-register-pair-invalid');reads.push({kind:'register',index:regs[at],bits:p.bits,type:p.type});at+=p.words}const result=dexTypeInfo(target.proto.returnType,{allowVoid:true}),writes=[],produced=[];if(result.category!=='void'){writes.push({kind:'runtime',name:'result',bits:result.bits,type:result.type});produced.push({bits:result.bits,type:result.type});nextResult={...result,nextOffset:byteOff+len*2,producerOperationId:b.operationId}}b={...b,locationReads:reads,locationWrites:writes,producedValues:produced,consumedValues:[],completeness:'exact',unknownEffects:[]}}catch(error){failure=error?.message??'dex-invoke-prototype-unresolved'}}
  for(const loc of [...(b.locationReads??[]),...(b.locationWrites??[])])if(loc.kind==='register'){const words=loc.bits===64?2:1;if(!Number.isSafeInteger(loc.index)||loc.index<0||loc.index+words>registersSize)failure=words===2?'dex-wide-register-pair-out-of-range':'dex-register-out-of-range'}
  if(failure)b=partial(b,failure);if(exceptionFailure)b={...b,completeness:b.completeness==='unknown'?'unknown':'partial',unknownEffects:[...(b.unknownEffects??[]),{category:'exceptions',reason:exceptionFailure}]};bundles.push(b);pendingResult=failure?null:nextResult;
 }
 return rebuild(base,bundles,exceptionFailure?[]:exceptionRegions,options);
}
