import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Installers.
 *
 * Rules these follow:
 *   - never overwrite a file without writing a `.before-jev-prune` backup;
 *   - never remove an entry we did not add (entries are identified by a marker);
 *   - never write a credential anywhere;
 *   - never change how a host authenticates unless explicitly asked.
 */

const MODULE_DIR = path.dirname(fileURLToPath(import.meta.url));
const JEV_ROOT = path.resolve(MODULE_DIR, "..");
const MARKER = "jev-context";

function readJsonIfPresent(filePath) {
  try {
    const parsed = JSON.parse(fs.readFileSync(filePath, "utf8"));
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch {
    return {};
  }
}

function readJsonForUninstall(filePath) {
  let raw;
  try {
    raw = fs.readFileSync(filePath, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") return null;
    throw new Error(`jev-prune uninstall: cannot read host hook config: ${filePath}`, { cause: error });
  }

  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw new Error(`jev-prune uninstall: malformed host hook config: ${filePath}`, { cause: error });
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`jev-prune uninstall: host hook config must be a JSON object: ${filePath}`);
  }
  return parsed;
}

function isOurs(entry) {
  if (!entry || typeof entry !== "object") return false;
  const candidates = [];
  if (typeof entry.command === "string") candidates.push(entry.command);
  if (Array.isArray(entry.hooks)) {
    for (const handler of entry.hooks) {
      if (handler && typeof handler.command === "string") candidates.push(handler.command);
    }
  }
  return candidates.some((command) => command.includes(MARKER));
}

function backup(filePath) {
  try {
    if (fs.existsSync(filePath)) {
      const backupPath = `${filePath}.before-jev-prune`;
      if (!fs.existsSync(backupPath)) fs.copyFileSync(filePath, backupPath);
      return backupPath;
    }
  } catch {
    /* ignore */
  }
  return null;
}

function writeJson(filePath, value) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const tmp = `${filePath}.${process.pid}.tmp`;
  fs.writeFileSync(tmp, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600 });
  fs.renameSync(tmp, filePath);
}

/* ------------------------------------------------------------------ OpenCode */

export function openCodePluginShimPath(root = process.cwd()) {
  return path.join(root, ".opencode", "plugin", "jev-prune.mjs");
}

/**
 * OpenCode discovers plugins from the project's `.opencode/plugin/` directory.
 * The shim is a two-line re-export so the plugin code stays in one place and
 * the engine is never duplicated into the host's tree.
 */
export function installOpenCode({ root = process.cwd() } = {}) {
  const shimPath = openCodePluginShimPath(root);
  const relative = path.relative(path.dirname(shimPath), path.join(JEV_ROOT, "adapters", "opencode", "plugin.mjs"));
  const contents = [
    `// Generated by jev-context/adapters/install.mjs — safe to delete.`,
    `export { default, id, JevPrunePlugin } from "./${relative.split(path.sep).join("/")}";`,
    ``,
  ].join("\n");
  backup(shimPath);
  fs.mkdirSync(path.dirname(shimPath), { recursive: true });
  fs.writeFileSync(shimPath, contents, { mode: 0o600 });
  return { host: "opencode", file: shimPath, wrote: contents };
}

function isManagedOpenCodeShim(contents) {
  if (typeof contents !== "string") return false;
  const lines = contents.trim().split("\n");
  return lines[0] === "// Generated by jev-context/adapters/install.mjs — safe to delete."
    && lines.length === 2
    && /^export \{ default, id, JevPrunePlugin \} from ".+jev-context\/adapters\/opencode\/plugin\.mjs";$/.test(lines[1]);
}

export function uninstallOpenCode({ root = process.cwd() } = {}) {
  const shimPath = openCodePluginShimPath(root);
  const backupPath = `${shimPath}.before-jev-prune`;
  let removed = false;
  let restored = false;
  try {
    if (!fs.existsSync(shimPath)) return { host: "opencode", file: shimPath, removed, restored };
    const current = fs.readFileSync(shimPath, "utf8");
    if (!isManagedOpenCodeShim(current)) {
      return { host: "opencode", file: shimPath, removed, restored };
    }
    if (fs.existsSync(backupPath)) {
      fs.copyFileSync(backupPath, shimPath);
      fs.unlinkSync(backupPath);
      restored = true;
    } else {
      fs.unlinkSync(shimPath);
    }
    removed = true;
  } catch {
    /* ignore */
  }
  return { host: "opencode", file: shimPath, removed, restored };
}

/* --------------------------------------------------------- Codex and Agy hooks */

/**
 * Which hook events each host is registered for, and whether each is async.
 *
 * The `async` flag is not cosmetic — it decides whether the host reads the
 * hook's stdout at all:
 *
 *   Codex 0.155.1 has no hook that can rewrite a shell/file tool result
 *   (PostToolUse offers only `updatedMCPToolOutput`), so every Codex hook is
 *   purely observational and therefore declared async. That also means the
 *   agent never waits on us. Codex pruning happens in the proxy.
 *
 *   Agy 1.2.7 *does* let PostToolUse rewrite the result, via `overwrite_result`
 *   — but only if the hook answers in time. Its PostToolUse entry must stay
 *   synchronous, or the capability is silently thrown away.
 *
 * Only events the adapter actually acts on are registered. A no-op hook costs a
 * process spawn per tool call and buys nothing.
 */
const HOST_HOOKS = {
  codex: [
    { event: "SessionStart", async: true },
    { event: "SessionEnd", async: true },
    { event: "PostToolUse", async: true },
  ],
  agy: [
    { event: "SessionStart", async: true },
    { event: "SessionEnd", async: true },
    { event: "PostToolUse", async: false, timeout: 8 },
  ],
};

const CODEX_EVENTS = HOST_HOOKS.codex.map((entry) => entry.event);
const AGY_EVENTS = HOST_HOOKS.agy.map((entry) => entry.event);

function hookHandlerSpec(host, { async: isAsync, timeout = 5 }) {
  const script = path.join(JEV_ROOT, "adapters", host, "hooks.mjs");
  const spec = { type: "command", command: `${process.execPath} ${script}`, timeout };
  if (isAsync) spec.async = true;
  return spec;
}

function mergeHooks(existing, host, events) {
  const next = { ...existing };
  const hooks = next.hooks && typeof next.hooks === "object" ? { ...next.hooks } : {};
  const added = [];
  const already = [];
  const specs = new Map((HOST_HOOKS[host] || []).map((entry) => [entry.event, entry]));

  for (const event of events) {
    const list = Array.isArray(hooks[event]) ? [...hooks[event]] : [];
    const present = list.some(isOurs);
    if (present) {
      already.push(event);
    } else {
      list.push({ hooks: [hookHandlerSpec(host, specs.get(event) || { async: true })] });
      added.push(event);
    }
    hooks[event] = list;
  }

  next.hooks = hooks;
  return { next, added, already };
}

function stripHooks(existing, events) {
  const next = { ...existing };
  if (!next.hooks || typeof next.hooks !== "object") return { next, removed: [] };
  const hooks = { ...next.hooks };
  const removed = [];
  for (const event of events) {
    if (!Array.isArray(hooks[event])) continue;
    const filtered = hooks[event].filter((entry) => !isOurs(entry));
    if (filtered.length !== hooks[event].length) removed.push(event);
    if (filtered.length === 0) delete hooks[event];
    else hooks[event] = filtered;
  }
  next.hooks = hooks;
  return { next, removed };
}

export function defaultCodexHome(env = process.env) {
  return env.CODEX_HOME || path.join(os.homedir(), ".codex");
}

export function installCodex({ codexHome = defaultCodexHome() } = {}) {
  const filePath = path.join(codexHome, "hooks.json");
  const existing = readJsonIfPresent(filePath);
  const { next, added, already } = mergeHooks(existing, "codex", CODEX_EVENTS);
  const backupPath = backup(filePath);
  writeJson(filePath, next);
  return { host: "codex", file: filePath, backup: backupPath, added, already };
}

export function uninstallCodex({ codexHome = defaultCodexHome() } = {}) {
  const filePath = path.join(codexHome, "hooks.json");
  const existing = readJsonForUninstall(filePath);
  if (existing === null) return { host: "codex", file: filePath, removed: [] };
  const { next, removed } = stripHooks(existing, CODEX_EVENTS);
  if (removed.length === 0) return { host: "codex", file: filePath, removed };
  const backupPath = backup(filePath);
  writeJson(filePath, next);
  return { host: "codex", file: filePath, backup: backupPath, removed };
}

export function defaultGeminiHome(env = process.env) {
  return env.GEMINI_HOME || path.join(os.homedir(), ".gemini");
}

export function installAgy({ geminiHome = defaultGeminiHome() } = {}) {
  const filePath = path.join(geminiHome, "config", "hooks.json");
  const existing = readJsonIfPresent(filePath);
  const { next, added, already } = mergeHooks(existing, "agy", AGY_EVENTS);
  const backupPath = backup(filePath);
  writeJson(filePath, next);
  return { host: "agy", file: filePath, backup: backupPath, added, already };
}

export function uninstallAgy({ geminiHome = defaultGeminiHome() } = {}) {
  const filePath = path.join(geminiHome, "config", "hooks.json");
  const existing = readJsonForUninstall(filePath);
  if (existing === null) return { host: "agy", file: filePath, removed: [] };
  const { next, removed } = stripHooks(existing, AGY_EVENTS);
  if (removed.length === 0) return { host: "agy", file: filePath, removed };
  const backupPath = backup(filePath);
  writeJson(filePath, next);
  return { host: "agy", file: filePath, backup: backupPath, removed };
}

/* ------------------------------------------------------- Codex provider sample */

/**
 * A Codex `model_providers` block that routes model traffic through the local
 * pruning proxy.
 *
 * This is *not* written into `config.toml` automatically: changing the model
 * provider changes how Codex authenticates upstream, and silently rewriting that
 * would be exactly the kind of destructive configuration edit this project
 * avoids. The sample is emitted next to the installer and the operator opts in.
 */
export function codexProviderSample({ proxyPort = 8787 } = {}) {
  return [
    "# Append to $CODEX_HOME/config.toml, then set:  model_provider = \"jev-prune\"",
    "#",
    "# `env_key` names the environment variable holding the UPSTREAM provider key;",
    "# the proxy forwards it unchanged. It is never stored by jev-prune.",
    "[model_providers.jev-prune]",
    'name = "jev-prune"',
    `base_url = "http://127.0.0.1:${proxyPort}/v1"`,
    'wire_api = "responses"',
    'env_key = "JEV_UPSTREAM_API_KEY"',
    "",
  ].join("\n");
}

export function writeCodexProviderSample(destination) {
  const target = destination || path.join(JEV_ROOT, "adapters", "codex", "config.sample.toml");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, codexProviderSample(), { mode: 0o600 });
  return target;
}

export { JEV_ROOT, CODEX_EVENTS, AGY_EVENTS, HOST_HOOKS };
