#!/usr/bin/env node
// freebuff isolated-HOME setup — idempotent restorer for ./freebuff-1..8.
//
// Background: ./freebuff-N used to be untracked shell wrappers with isolated
// HOME dirs at /mnt/workspace/.freebuff-homes (outside the repo). Untracked
// files inside the repo are wiped by repo sync/clean, so the commands broke.
// This script is the single source of truth:
//   - isolated HOME root: /mnt/workspace/.dev-state/freebuff-homes/N/home.
//     It MUST stay outside both the repo (git clean/reset can't reach it) and
//     the launch cwd: freebuff >=0.0.175 shows a "Select project directory"
//     picker on startup iff HOME is inside cwd (the showProjectPicker gate:
//     MhA(cwd,homedir): relative(cwd,homedir) has no leading "..").
//   - one shared binary: shared/manicode/freebuff. Each HOME would otherwise
//     download its own ~140MB copy; instead the newest available copy is kept
//     once in shared/ and missing per-HOME binaries become symlinks to it
//     (the launcher treats a symlink as installed; a later background update
//     atomically replaces the link with a per-HOME copy for that HOME only).
//   - tracked wrappers: <repo>/freebuff-1..8 (regenerated here, must be committed)
//   - launcher: <repo>/.tools/npm/bin/freebuff (reinstalled on demand)
//   - one-time migration of small identity files from the legacy outside path.
//   - off-repo mirror: /mnt/workspace/.dev-state/freebuff-restore/ (survives
//     git clean/reset; auto-heal hook in .persistent-bashrc restores from it).
//
// Usage:
//   node scripts/freebuff-setup.mjs            ensure all 1..8 + launcher + wrappers
//   node scripts/freebuff-setup.mjs --ensure N  fast path for wrappers (one HOME + launcher)
//   npm run freebuff:setup                      same as the first form
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA_ROOT = '/mnt/workspace/.dev-state/freebuff-homes';
const SHARED_ROOT = path.join(DATA_ROOT, 'shared');
// Previous data location inside the repo (kept as a migration source only;
// HOME under cwd triggers freebuff's startup project picker, so data must
// not live there).
const REPO_DATA_ROOT = path.join(ROOT, '.freebuff-homes');
const LEGACY_ROOT = '/mnt/workspace/.freebuff-homes';
const MIRROR_ROOT = '/mnt/workspace/.dev-state/freebuff-restore';
const NUMS = ['1', '2', '3', '4', '5', '6', '7', '8'];

// Small identity/config files worth migrating. Everything else is either a
// re-downloadable binary (freebuff, ~140MB per HOME) or regenerable cache
// (.graft, chat projects history).
const HOME_FILES = [
  '.config/manicode/analytics-id.json',
  '.config/manicode/credentials.json',
  '.config/manicode/settings.json',
  '.config/manicode/freebuff-metadata.json',
  '.config/manicode/freebuff-instance-owner.json',
  '.local/state/gh/device-id',
];
const SHARED_FILES = [
  'history/message-history.json',
  'manicode/rg',
  'manicode/tree-sitter.wasm',
];
const SHARED_BIN = path.join(SHARED_ROOT, 'manicode', 'freebuff');
const SHARED_BIN_VERSION = path.join(SHARED_ROOT, 'manicode', 'freebuff.version');
// Source files mirrored off-repo so git clean/reset cannot destroy the
// restorer itself. Wrappers are generated, not mirrored (they embed no state).
const MIRRORED = ['scripts/freebuff-setup.mjs', 'tests/freebuff-wrappers.mjs'];

export function wrapperScript(n) {
  return `#!/usr/bin/env bash
# freebuff-${n} — isolated-HOME wrapper (tracked).
# HOME lives under /mnt/workspace/.dev-state: outside the repo (git
# clean/reset can't wipe it) and outside the launch cwd (otherwise freebuff
# shows its "Select project directory" picker on every startup).
# DO NOT EDIT: regenerated by scripts/freebuff-setup.mjs (npm run freebuff:setup).
set -euo pipefail
N="${n}"
REPO="$(cd "$(dirname "\${BASH_SOURCE[0]:-$0}")" && pwd)"
FB_HOME="/mnt/workspace/.dev-state/freebuff-homes/$N/home"
node "$REPO/scripts/freebuff-setup.mjs" --ensure "$N"
export HOME="$FB_HOME"
# freebuff always starts in the repo root, wherever the wrapper is invoked from.
cd "$REPO"
exec "$REPO/.tools/npm/bin/freebuff" "$@"
`;
}

function pathIsWithin(root, target) {
  const relative = path.relative(path.resolve(root), path.resolve(target));
  return relative === '' || (!path.isAbsolute(relative) && relative !== '..' && !relative.startsWith(`..${path.sep}`));
}

function directoryIdentity(entry) {
  return Object.freeze({ dev:String(entry.dev), ino:String(entry.ino) });
}

function sameDirectoryIdentity(entry, expected) {
  return !entry.isSymbolicLink() && entry.isDirectory()
    && String(entry.dev) === expected.dev && String(entry.ino) === expected.ino;
}

export function captureSafeDirectoryIdentity(root, target, { fsImpl = fs } = {}) {
  const resolvedRoot = path.resolve(root);
  const resolvedTarget = path.resolve(target);
  if (!pathIsWithin(resolvedRoot, resolvedTarget)) {
    throw new Error(`freebuff setup: unsafe directory outside containment root: ${resolvedTarget}`);
  }

  let rootEntry = null;
  try {
    rootEntry = fsImpl.lstatSync(resolvedRoot);
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error;
    fsImpl.mkdirSync(resolvedRoot, { recursive:true });
    rootEntry = fsImpl.lstatSync(resolvedRoot);
  }
  if (rootEntry.isSymbolicLink() || !rootEntry.isDirectory()) {
    throw new Error(`freebuff setup: unsafe containment root is not a real directory: ${resolvedRoot}`);
  }

  const components = [{ path:resolvedRoot, ...directoryIdentity(rootEntry) }];
  const relative = path.relative(resolvedRoot, resolvedTarget);
  let current = resolvedRoot;
  for (const part of relative ? relative.split(path.sep) : []) {
    current = path.join(current, part);
    let entry;
    try {
      entry = fsImpl.lstatSync(current);
    } catch (error) {
      if (error?.code !== 'ENOENT') throw error;
      fsImpl.mkdirSync(current);
      entry = fsImpl.lstatSync(current);
    }
    if (entry.isSymbolicLink() || !entry.isDirectory()) {
      throw new Error(`freebuff setup: unsafe directory ancestor: ${current}`);
    }
    components.push({ path:current, ...directoryIdentity(entry) });
  }
  return Object.freeze({
    root:resolvedRoot,
    target:resolvedTarget,
    components:Object.freeze(components.map((component) => Object.freeze(component))),
  });
}

export function assertSafeDirectoryIdentity(snapshot, { fsImpl = fs } = {}) {
  for (const expected of snapshot.components) {
    let entry;
    try {
      entry = fsImpl.lstatSync(expected.path);
    } catch (error) {
      const changed = new Error(`freebuff setup: directory identity changed: ${expected.path}`);
      changed.code = 'FREEBUFF_DIRECTORY_IDENTITY_CHANGED';
      changed.cause = error;
      throw changed;
    }
    if (!sameDirectoryIdentity(entry, expected)) {
      const changed = new Error(`freebuff setup: directory identity changed: ${expected.path}`);
      changed.code = 'FREEBUFF_DIRECTORY_IDENTITY_CHANGED';
      throw changed;
    }
  }
  return true;
}

export function ensureSafeDirectory(root, target, { fsImpl = fs } = {}) {
  return captureSafeDirectoryIdentity(root, target, { fsImpl }).target;
}

function stableDirectoryDescriptorPath(fd, platform = process.platform) {
  if (platform === 'linux') return `/proc/self/fd/${fd}`;
  if (platform === 'darwin') return `/dev/fd/${fd}`;
  throw new Error(`freebuff setup: stable directory descriptor paths are unsupported on ${platform}`);
}

export function openSafeDirectory(root, target, { fsImpl = fs, platform = process.platform } = {}) {
  const snapshot = captureSafeDirectoryIdentity(root, target, { fsImpl });
  const expected = snapshot.components.at(-1);
  const fd = fsImpl.openSync(snapshot.target, 'r');
  try {
    const opened = fsImpl.fstatSync(fd);
    if (!sameDirectoryIdentity(opened, expected)) {
      throw Object.assign(new Error(`freebuff setup: directory identity changed before open: ${snapshot.target}`), {
        code:'FREEBUFF_DIRECTORY_IDENTITY_CHANGED',
      });
    }
    const descriptorPath = stableDirectoryDescriptorPath(fd, platform);
    return Object.freeze({
      snapshot,
      fd,
      descriptorPath,
      child(name) { return path.join(descriptorPath, name); },
      close() { fsImpl.closeSync(fd); },
    });
  } catch (error) {
    try { fsImpl.closeSync(fd); } catch {}
    throw error;
  }
}

export function copyIfMissing(src, dst, executable = false, containmentRoot = null, { fsImpl = fs } = {}) {
  const dir = path.dirname(dst);
  const safeDir = openSafeDirectory(containmentRoot ?? dir, dir, { fsImpl });
  const stableDst = safeDir.child(path.basename(dst));
  try {
    try { fsImpl.lstatSync(stableDst); return false; }
    catch (error) { if (error?.code !== 'ENOENT') return false; }
    if (!fsImpl.existsSync(src)) return false;
    try { fsImpl.copyFileSync(src, stableDst, fsImpl.constants.COPYFILE_EXCL); }
    catch (error) { if (error?.code === 'EEXIST') return false; throw error; }
    if (executable) fsImpl.chmodSync(stableDst, 0o755);
    else if (dst.endsWith('.json')) { try { fsImpl.chmodSync(stableDst, 0o600); } catch {} }
    try { assertSafeDirectoryIdentity(safeDir.snapshot, { fsImpl }); }
    catch (error) { try { fsImpl.rmSync(stableDst, { force:true }); } catch {} throw error; }
    return true;
  } finally {
    safeDir.close();
  }
}

// Legacy homes use absolute symlinks into the legacy shared dir; recreate
// them as repo-relative links into the repo-local shared dir.
export function replaceWithSymlinkAtomically(linkPath, target, { fsImpl = fs, safeDirectory = null } = {}) {
  const dir = path.dirname(linkPath);
  const ownedDir = safeDirectory ?? openSafeDirectory(dir, dir, { fsImpl });
  const ownsHandle = !safeDirectory;
  const base = path.basename(linkPath);
  const token = `${process.pid}-${randomUUID()}`;
  const stableLink = ownedDir.child(base);
  const staged = ownedDir.child(`.${base}.link-${token}`);
  const backup = ownedDir.child(`.${base}.backup-${token}`);
  let backedUp = false;
  let published = false;
  try {
    fsImpl.symlinkSync(target, staged);
    try {
      fsImpl.lstatSync(stableLink);
      fsImpl.renameSync(stableLink, backup);
      backedUp = true;
    } catch (error) {
      if (error?.code !== 'ENOENT') throw error;
    }
    try {
      fsImpl.renameSync(staged, stableLink);
      published = true;
      assertSafeDirectoryIdentity(ownedDir.snapshot, { fsImpl });
    } catch (error) {
      if (backedUp) {
        try { fsImpl.renameSync(backup, stableLink); backedUp = false; }
        catch (restoreError) { error.cause = restoreError; }
      }
      throw error;
    }
    if (backedUp) {
      try { fsImpl.rmSync(backup, { recursive:true, force:true }); backedUp = false; } catch {}
    }
    return true;
  } finally {
    if (!published) { try { fsImpl.rmSync(staged, { force:true }); } catch {} }
    if (published && backedUp) { try { fsImpl.rmSync(backup, { recursive:true, force:true }); } catch {} }
    if (ownsHandle) ownedDir.close();
  }
}

export function cleanupSymlinkBackups(linkPath, { fsImpl = fs, safeDirectory = null } = {}) {
  const dir = path.dirname(linkPath);
  const ownedDir = safeDirectory ?? openSafeDirectory(dir, dir, { fsImpl });
  const ownsHandle = !safeDirectory;
  const prefix = `.${path.basename(linkPath)}.backup-`;
  let clean = true;
  try {
    let names = [];
    try { names = fsImpl.readdirSync(ownedDir.descriptorPath); } catch { return false; }
    for (const name of names) {
      if (!name.startsWith(prefix)) continue;
      try { fsImpl.rmSync(ownedDir.child(name), { recursive:true, force:true }); }
      catch { clean = false; }
    }
    return clean;
  } finally {
    if (ownsHandle) ownedDir.close();
  }
}

export function ensureHomeLinks(homeDir, { fsImpl = fs } = {}) {
  const manicode = path.join(homeDir, '.config', 'manicode');
  const safeDir = openSafeDirectory(homeDir, manicode, { fsImpl });
  const links = {
    'message-history.json': '../../../../shared/history/message-history.json',
    projects: '../../../../shared/history/projects',
    rg: '../../../../shared/manicode/rg',
  };
  try {
    for (const [name, target] of Object.entries(links)) {
      const linkPath = path.join(manicode, name);
      const stableLink = safeDir.child(name);
      cleanupSymlinkBackups(linkPath, { fsImpl, safeDirectory:safeDir });
      let entry = null;
      try { entry = fsImpl.lstatSync(stableLink); }
      catch (error) { if (error?.code !== 'ENOENT') throw error; }
      if (entry?.isSymbolicLink() && fsImpl.readlinkSync(stableLink) === target) continue;
      replaceWithSymlinkAtomically(linkPath, target, { fsImpl, safeDirectory:safeDir });
    }
  } finally {
    safeDir.close();
  }
}

export function moveDirectoryIfMissing(src, dst, { containmentRoot = DATA_ROOT, fsImpl = fs } = {}) {
  let dstEntry = null;
  try { dstEntry = fsImpl.lstatSync(dst); }
  catch (error) { if (error?.code !== 'ENOENT') throw error; }
  if (dstEntry) return false;
  let srcEntry;
  try { srcEntry = fsImpl.lstatSync(src); }
  catch (error) { if (error?.code === 'ENOENT') return false; throw error; }
  if (srcEntry.isSymbolicLink() || !srcEntry.isDirectory()) {
    throw new Error(`freebuff setup: migration source is not a real directory: ${src}`);
  }
  const dir = path.dirname(dst);
  const safeDir = openSafeDirectory(containmentRoot, dir, { fsImpl });
  try {
    const stableDst = safeDir.child(path.basename(dst));
    fsImpl.renameSync(src, stableDst);
    try { assertSafeDirectoryIdentity(safeDir.snapshot, { fsImpl }); }
    catch (error) { try { fsImpl.renameSync(stableDst, src); } catch (restoreError) { error.cause = restoreError; } throw error; }
    return true;
  } finally {
    safeDir.close();
  }
}

function moveIfMissing(src, dst, containmentRoot = path.dirname(dst)) {
  if (fs.existsSync(dst) || !fs.existsSync(src)) return false;
  const dir = path.dirname(dst);
  let safeDir;
  try {
    safeDir = openSafeDirectory(containmentRoot, dir);
    fs.renameSync(src, safeDir.child(path.basename(dst)));
    return true;
  } catch {
    return false;
  } finally {
    try { safeDir?.close(); } catch {}
  }
}

export function cmpVersions(a, b) {
  const pa = a.split('.').map((part) => BigInt(part));
  const pb = b.split('.').map((part) => BigInt(part));
  for (let i = 0; i < 3; i++) {
    if (pa[i] !== pb[i]) return pa[i] < pb[i] ? -1 : 1;
  }
  return 0;
}

export function newerVersionCandidate(current, candidate) {
  return !current || cmpVersions(current.version, candidate.version) < 0 ? candidate : current;
}

function isSafeExistingPath(root, target) {
  const resolvedRoot = path.resolve(root);
  const resolvedTarget = path.resolve(target);
  if (!pathIsWithin(resolvedRoot, resolvedTarget)) return false;
  try {
    const rootEntry = fs.lstatSync(resolvedRoot);
    if (rootEntry.isSymbolicLink() || !rootEntry.isDirectory()) return false;
    const relative = path.relative(resolvedRoot, resolvedTarget);
    const parts = relative ? relative.split(path.sep) : [];
    let current = resolvedRoot;
    for (let i = 0; i < parts.length; i++) {
      current = path.join(current, parts[i]);
      const entry = fs.lstatSync(current);
      if (entry.isSymbolicLink()) return false;
      if (i < parts.length - 1 && !entry.isDirectory()) return false;
    }
    return true;
  } catch {
    return false;
  }
}

function realBinary(p, containmentRoot = null) {
  try {
    if (containmentRoot && !isSafeExistingPath(containmentRoot, p)) return false;
    return fs.statSync(p).isFile() && !fs.lstatSync(p).isSymbolicLink();
  } catch {
    return false;
  }
}

function binaryVersion(bin) {
  try {
    const r = spawnSync(bin, ['--version'], { encoding: 'utf8', timeout: 30000 });
    const v = (r.stdout || '').trim().split('\n')[0].trim();
    return /^\d+\.\d+\.\d+$/.test(v) ? v : null;
  } catch {
    return null;
  }
}

export function publishExecutableAtomically(src, dst, expectedVersion, {
  versionProbe = binaryVersion,
  fsImpl = fs,
  containmentRoot = path.dirname(dst),
} = {}) {
  const dir = path.dirname(dst);
  const safeDir = openSafeDirectory(containmentRoot, dir, { fsImpl });
  const base = path.basename(dst);
  const stableDst = safeDir.child(base);
  const tmp = safeDir.child(`.${base}.tmp-${process.pid}-${randomUUID()}`);
  try {
    fsImpl.copyFileSync(src, tmp, fsImpl.constants.COPYFILE_EXCL);
    fsImpl.chmodSync(tmp, 0o755);
    const stagedVersion = versionProbe(tmp);
    if (expectedVersion && stagedVersion !== expectedVersion) {
      throw new Error(`freebuff setup: staged shared binary version mismatch (${stagedVersion || 'unknown'} != ${expectedVersion})`);
    }
    fsImpl.renameSync(tmp, stableDst);
    assertSafeDirectoryIdentity(safeDir.snapshot, { fsImpl });
    return stagedVersion;
  } finally {
    try { fsImpl.rmSync(tmp, { force:true }); } catch {}
    safeDir.close();
  }
}

export function publishTextAtomically(dst, content, mode = 0o600, {
  fsImpl = fs,
  containmentRoot = path.dirname(dst),
} = {}) {
  const dir = path.dirname(dst);
  const safeDir = openSafeDirectory(containmentRoot, dir, { fsImpl });
  const base = path.basename(dst);
  const stableDst = safeDir.child(base);
  const tmp = safeDir.child(`.${base}.tmp-${process.pid}-${randomUUID()}`);
  try {
    fsImpl.writeFileSync(tmp, content, { flag:'wx', mode });
    fsImpl.renameSync(tmp, stableDst);
    assertSafeDirectoryIdentity(safeDir.snapshot, { fsImpl });
    return true;
  } finally {
    try { fsImpl.rmSync(tmp, { force:true }); } catch {}
    safeDir.close();
  }
}

// Keep one shared binary copy; returns { path, version } or null when no
// usable copy exists anywhere yet (first launch then downloads for its HOME).
function ensureSharedBinary() {
  ensureSafeDirectory(DATA_ROOT, path.dirname(SHARED_BIN));
  let sharedBest = null;
  if (realBinary(SHARED_BIN, SHARED_ROOT)) {
    const v = binaryVersion(SHARED_BIN) || (() => {
      try { return fs.readFileSync(SHARED_BIN_VERSION, 'utf8').trim() || null; } catch { return null; }
    })();
    if (v) {
      sharedBest = { path: SHARED_BIN, version: v };
    }
  }

  let best = sharedBest;
  for (const base of [DATA_ROOT, LEGACY_ROOT]) {
    for (const n of NUMS) {
      const p = path.join(base, n, 'home', '.config', 'manicode', 'freebuff');
      if (!realBinary(p, base)) continue;
      const v = binaryVersion(p);
      if (!v) continue;
      best = newerVersionCandidate(best, { path: p, version: v });
    }
  }
  if (!best) return null;
  if (!sharedBest || best.path !== SHARED_BIN || cmpVersions(sharedBest.version, best.version) < 0) {
    try {
      if (best.path !== SHARED_BIN) {
        // Stage in the shared directory, validate the complete executable, and
        // only then atomically rename over the live path. Existing HOME links
        // therefore observe complete old-or-new bytes, never an in-place copy.
        publishExecutableAtomically(best.path, SHARED_BIN, best.version, { containmentRoot:SHARED_ROOT });
      }
    } catch {
      return sharedBest;
    }
    try {
      publishTextAtomically(SHARED_BIN_VERSION, `${best.version}\n`, 0o600, { containmentRoot:SHARED_ROOT });
    } catch {
      // The executable itself is authoritative. A later setup can repair the
      // advisory sidecar without downgrading a successfully published binary.
    }
    return { path: SHARED_BIN, version: best.version };
  }
  return sharedBest;
}

export function ensureMetadata(dir, shared, containmentRoot = dir, { fsImpl = fs } = {}) {
  const safeDir = openSafeDirectory(containmentRoot, dir, { fsImpl });
  const metaPath = safeDir.child('freebuff-metadata.json');
  const expectedTarget = `${process.platform}-${process.arch}`;
  try {
    let currentEntry = null;
    try { currentEntry = fsImpl.lstatSync(metaPath); }
    catch (error) { if (error?.code !== 'ENOENT') return false; }
    if (currentEntry?.isFile()) {
      try {
        const cur = JSON.parse(fsImpl.readFileSync(metaPath, 'utf8'));
        if (cur.version === shared.version && cur.target === expectedTarget) return false;
      } catch {}
    }
    const content = `${JSON.stringify({ version:shared.version, target:expectedTarget }, null, 2)}\n`;
    const tmp = safeDir.child(`.freebuff-metadata.json.tmp-${process.pid}-${randomUUID()}`);
    try {
      fsImpl.writeFileSync(tmp, content, { flag:'wx', mode:0o600 });
      fsImpl.renameSync(tmp, metaPath);
      assertSafeDirectoryIdentity(safeDir.snapshot, { fsImpl });
      return true;
    } catch {
      return false;
    } finally {
      try { fsImpl.rmSync(tmp, { force:true }); } catch {}
    }
  } finally {
    safeDir.close();
  }
}

// Point a HOME without its own binary at the shared copy (+ matching
// metadata so the launcher accepts it without re-downloading). Real binaries
// and their future background updates are left alone.
function linkSharedBinary(home, shared) {
  const dir = path.join(home, '.config', 'manicode');
  const directoryIdentity = captureSafeDirectoryIdentity(home, dir);
  const guard = () => assertSafeDirectoryIdentity(directoryIdentity);
  const bin = path.join(dir, 'freebuff');
  let linked = false;
  try {
    guard();
    const st = fs.lstatSync(bin);
    if (!st.isSymbolicLink()) return false;
    if (fs.readlinkSync(bin) !== shared.path) {
      guard();
      fs.rmSync(bin, { force:true });
      guard();
      fs.symlinkSync(shared.path, bin);
      guard();
      linked = true;
    }
  } catch {
    try {
      guard();
      fs.symlinkSync(shared.path, bin);
      guard();
      linked = true;
    } catch {
      return false;
    }
  }
  const metaUpdated = ensureMetadata(dir, shared, home);
  return linked || metaUpdated;
}

function ensureShared() {
  ensureSafeDirectory(DATA_ROOT, SHARED_ROOT);
  let migrated = 0;
  const repoShared = path.join(REPO_DATA_ROOT, 'shared');
  for (const rel of SHARED_FILES) {
    const dst = path.join(SHARED_ROOT, rel);
    ensureSafeDirectory(SHARED_ROOT, path.dirname(dst));
    if (fs.existsSync(dst)) continue;
    if (moveIfMissing(path.join(repoShared, rel), dst, SHARED_ROOT)) {
      migrated++;
      continue;
    }
    const src = path.join(LEGACY_ROOT, 'shared', rel);
    if (copyIfMissing(src, dst, !rel.endsWith('.json'), SHARED_ROOT)) migrated++;
  }
  ensureSafeDirectory(SHARED_ROOT, path.join(SHARED_ROOT, 'history', 'projects'));
  return migrated;
}

function ensureHome(n, shared) {
  const home = path.join(DATA_ROOT, n, 'home');
  const repoHome = path.join(REPO_DATA_ROOT, n, 'home');
  const legacy = path.join(LEGACY_ROOT, n, 'home');
  let migrated = 0;

  // Persistent HOME ancestors are untrusted state. Validate each directory
  // entry without following symlinks before any migration or child mutation.
  ensureSafeDirectory(DATA_ROOT, path.dirname(home));
  let homeExists = false;
  try {
    const homeEntry = fs.lstatSync(home);
    if (homeEntry.isSymbolicLink() || !homeEntry.isDirectory()) {
      throw new Error(`freebuff setup: unsafe HOME entry: ${home}`);
    }
    homeExists = true;
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error;
  }

  if (!homeExists && moveDirectoryIfMissing(repoHome, home)) {
    migrated++;
  }
  ensureSafeDirectory(DATA_ROOT, home);
  if (fs.existsSync(repoHome)) {
    for (const rel of HOME_FILES) {
      if (copyIfMissing(path.join(repoHome, rel), path.join(home, rel), false, home)) migrated++;
    }
  }
  const sharedMigrated = ensureShared();
  for (const rel of HOME_FILES) {
    if (copyIfMissing(path.join(legacy, rel), path.join(home, rel), false, home)) migrated++;
  }
  ensureHomeLinks(home);
  if (shared && linkSharedBinary(home, shared)) migrated++;
  // Drop download residue possibly carried over by the move.
  try {
    const dir = path.join(home, '.config', 'manicode');
    for (const e of fs.readdirSync(dir)) {
      if (e.endsWith('.part') || e === '.freebuff-download-temp') {
        fs.rmSync(path.join(dir, e), { recursive: true, force: true });
      }
    }
  } catch {}
  return { migrated: migrated + sharedMigrated };
}

function cleanupRepoData() {
  // Remove the old in-repo data root once every number has moved out and
  // no unmigrated HOME_FILES remain in REPO_DATA_ROOT.
  try {
    if (!fs.existsSync(REPO_DATA_ROOT)) return false;
    for (const n of NUMS) {
      if (!fs.existsSync(path.join(DATA_ROOT, n, 'home', '.config', 'manicode', 'credentials.json'))) return false;
      const repoHome = path.join(REPO_DATA_ROOT, n, 'home');
      if (fs.existsSync(repoHome)) {
        for (const rel of HOME_FILES) {
          const repoFile = path.join(repoHome, rel);
          const dstFile = path.join(DATA_ROOT, n, 'home', rel);
          if (fs.existsSync(repoFile) && !fs.existsSync(dstFile)) return false;
        }
      }
    }
    fs.rmSync(REPO_DATA_ROOT, { recursive: true, force: true });
    return true;
  } catch {
    return false;
  }
}

function ensureLauncher() {
  const launcher = path.join(ROOT, '.tools', 'npm', 'bin', 'freebuff');
  try {
    const st = fs.statSync(launcher);
    if (st.isFile()) return false;
    fs.rmSync(launcher, { recursive: true, force: true });
  } catch {}
  fs.mkdirSync(path.join(ROOT, '.tools', 'npm'), { recursive: true });
  const r = spawnSync('npm', ['install', '-g', '--prefix', path.join(ROOT, '.tools', 'npm'), 'freebuff@latest'], {
    cwd: ROOT,
    stdio: 'inherit',
  });
  if (r.status !== 0) {
    console.error('freebuff launcher install failed');
    process.exit(r.status ?? 1);
  }
  return true;
}

export function ensureWrappers(root = ROOT) {
  let wrote = 0;
  for (const n of NUMS) {
    const p = path.join(root, `freebuff-${n}`);
    const content = wrapperScript(n);
    let entry = null;
    try {
      entry = fs.lstatSync(p);
    } catch (error) {
      if (error?.code !== 'ENOENT') throw error;
    }

    let healthy = false;
    if (entry?.isFile() && !entry.isSymbolicLink()) {
      const cur = fs.readFileSync(p, 'utf8');
      healthy = cur === content && (entry.mode & 0o111) !== 0;
    }
    if (healthy) continue;

    // Never write/chmod through the existing wrapper leaf. A same-directory
    // exclusive temp file followed by rename replaces a symlink entry itself,
    // leaving any external target untouched and publishing complete bytes.
    publishTextAtomically(p, content, 0o755, { containmentRoot:root });
    wrote++;
  }
  return wrote;
}

function ensureMirror() {
  let wrote = 0;
  try {
    for (const rel of MIRRORED) {
      const src = path.join(ROOT, rel);
      const dst = path.join(MIRROR_ROOT, rel);
      const content = fs.readFileSync(src, 'utf8');
      try {
        const st = fs.lstatSync(dst);
        if (st.isSymbolicLink()) {
          fs.rmSync(dst, { force: true });
        } else if (st.isFile()) {
          const cur = fs.readFileSync(dst, 'utf8');
          if (cur === content) continue;
        }
      } catch {}
      fs.mkdirSync(path.dirname(dst), { recursive: true });
      const tmp = `${dst}.tmp-${process.pid}-${Date.now()}`;
      fs.writeFileSync(tmp, content);
      fs.renameSync(tmp, dst);
      wrote++;
    }
  } catch {}
  return wrote;
}

export function parseArgs(argv = process.argv.slice(2)) {
  if (argv.length === 0) {
    return { mode: 'full' };
  }
  if (argv[0] === '--ensure') {
    if (argv.length === 2 && NUMS.includes(argv[1])) {
      return { mode: 'ensure', num: argv[1] };
    }
    const target = argv.length > 1 ? argv.slice(1).join(' ') : '<missing>';
    throw new Error(`freebuff setup: invalid --ensure selector '${target}'. Expected one of: ${NUMS.join(', ')}`);
  }
  throw new Error(`freebuff setup: unrecognized argument(s) '${argv.join(' ')}'. Usage: freebuff-setup.mjs [--ensure 1..8]`);
}

export function run(argv = process.argv.slice(2)) {
  const parsed = parseArgs(argv);
  if (parsed.mode === 'ensure') {
    ensureShared();
    ensureHome(parsed.num, ensureSharedBinary());
    ensureLauncher();
    return { mode: 'ensure', num: parsed.num };
  }

  const shared = ensureSharedBinary();
  let totalMigrated = 0;
  for (const n of NUMS) totalMigrated += ensureHome(n, shared).migrated;
  const repoCleaned = cleanupRepoData();
  const launcherInstalled = ensureLauncher();
  const wrappersWrote = ensureWrappers();
  const mirrored = ensureMirror();
  const summary = `freebuff setup: migrated=${totalMigrated} repo-data-removed=${repoCleaned} launcher=${launcherInstalled ? 'installed' : 'ok'} wrappers=${wrappersWrote} mirror=${mirrored} (re)wrote`;
  console.log(summary);
  return {
    mode: 'full',
    migrated: totalMigrated,
    repoCleaned,
    launcherInstalled,
    wrappersWrote,
    mirrored,
    summary,
  };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    run();
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
}
