#!/usr/bin/env node
// freebuff isolated-HOME setup — idempotent restorer for ./freebuff-1..8.
//
// Background: ./freebuff-N used to be untracked shell wrappers with isolated
// HOME dirs at /mnt/workspace/.freebuff-homes (outside the repo). Untracked
// files inside the repo are wiped by repo sync/clean, so the commands broke.
// This script is the single source of truth:
//   - isolated HOME root: /mnt/workspace/.dev-state/freebuff-homes/N/home.
//     It MUST stay outside both the repo (git clean/reset can't reach it) and
//     the launch cwd: freebuff >=0.0.175 shows a "Select project directory"
//     picker on startup iff HOME is inside cwd (the showProjectPicker gate:
//     MhA(cwd,homedir): relative(cwd,homedir) has no leading "..").
//   - one shared binary: shared/manicode/freebuff. Each HOME would otherwise
//     download its own ~140MB copy; instead the newest available copy is kept
//     once in shared/ and missing per-HOME binaries become symlinks to it
//     (the launcher treats a symlink as installed; a later background update
//     atomically replaces the link with a per-HOME copy for that HOME only).
//   - tracked wrappers: <repo>/freebuff-1..8 (regenerated here, must be committed)
//   - launcher: <repo>/.tools/npm/bin/freebuff (reinstalled on demand)
//   - one-time migration of small identity files from the legacy outside path.
//   - off-repo mirror: /mnt/workspace/.dev-state/freebuff-restore/ (survives
//     git clean/reset; auto-heal hook in .persistent-bashrc restores from it).
//
// Usage:
//   node scripts/freebuff-setup.mjs            ensure all 1..8 + launcher + wrappers
//   node scripts/freebuff-setup.mjs --ensure N  fast path for wrappers (one HOME + launcher)
//   npm run freebuff:setup                      same as the first form
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA_ROOT = '/mnt/workspace/.dev-state/freebuff-homes';
const SHARED_ROOT = path.join(DATA_ROOT, 'shared');
// Previous data location inside the repo (kept as a migration source only;
// HOME under cwd triggers freebuff's startup project picker, so data must
// not live there).
const REPO_DATA_ROOT = path.join(ROOT, '.freebuff-homes');
const LEGACY_ROOT = '/mnt/workspace/.freebuff-homes';
const MIRROR_ROOT = '/mnt/workspace/.dev-state/freebuff-restore';
const NUMS = ['1', '2', '3', '4', '5', '6', '7', '8'];

// Small identity/config files worth migrating. Everything else is either a
// re-downloadable binary (freebuff, ~140MB per HOME) or regenerable cache
// (.graft, chat projects history).
const HOME_FILES = [
  '.config/manicode/analytics-id.json',
  '.config/manicode/credentials.json',
  '.config/manicode/settings.json',
  '.config/manicode/freebuff-metadata.json',
  '.config/manicode/freebuff-instance-owner.json',
  '.local/state/gh/device-id',
];
const SHARED_FILES = [
  'history/message-history.json',
  'manicode/rg',
  'manicode/tree-sitter.wasm',
];
const SHARED_BIN = path.join(SHARED_ROOT, 'manicode', 'freebuff');
const SHARED_BIN_VERSION = path.join(SHARED_ROOT, 'manicode', 'freebuff.version');
// Source files mirrored off-repo so git clean/reset cannot destroy the
// restorer itself. Wrappers are generated, not mirrored (they embed no state).
const MIRRORED = ['scripts/freebuff-setup.mjs', 'tests/freebuff-wrappers.mjs'];

function wrapperScript(n) {
  return `#!/usr/bin/env bash
# freebuff-${n} — isolated-HOME wrapper (tracked).
# HOME lives under /mnt/workspace/.dev-state: outside the repo (git
# clean/reset can't wipe it) and outside the launch cwd (otherwise freebuff
# shows its "Select project directory" picker on every startup).
# DO NOT EDIT: regenerated by scripts/freebuff-setup.mjs (npm run freebuff:setup).
set -euo pipefail
N="${n}"
REPO="$(cd "$(dirname "\${BASH_SOURCE[0]:-$0}")" && pwd)"
FB_HOME="/mnt/workspace/.dev-state/freebuff-homes/$N/home"
node "$REPO/scripts/freebuff-setup.mjs" --ensure "$N"
export HOME="$FB_HOME"
# freebuff always starts in the repo root, wherever the wrapper is invoked from.
cd "$REPO"
exec "$REPO/.tools/npm/bin/freebuff" "$@"
`;
}

export function copyIfMissing(src, dst, executable = false) {
  // Destination occupancy must be checked without following the final symlink.
  // COPYFILE_EXCL closes the race between the lstat and the actual copy.
  try {
    fs.lstatSync(dst);
    return false;
  } catch (error) {
    if (error?.code !== 'ENOENT') return false;
  }
  if (!fs.existsSync(src)) return false;
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  try {
    fs.copyFileSync(src, dst, fs.constants.COPYFILE_EXCL);
  } catch (error) {
    if (error?.code === 'EEXIST') return false;
    throw error;
  }
  if (executable) fs.chmodSync(dst, 0o755);
  else if (dst.endsWith('.json')) {
    try {
      fs.chmodSync(dst, 0o600);
    } catch {}
  }
  return true;
}

// Legacy homes use absolute symlinks into the legacy shared dir; recreate
// them as repo-relative links into the repo-local shared dir.
function ensureHomeLinks(homeDir) {
  const manicode = path.join(homeDir, '.config', 'manicode');
  fs.mkdirSync(manicode, { recursive: true });
  const links = {
    'message-history.json': '../../../../shared/history/message-history.json',
    projects: '../../../../shared/history/projects',
    rg: '../../../../shared/manicode/rg',
  };
  for (const [name, target] of Object.entries(links)) {
    const p = path.join(manicode, name);
    try {
      if (fs.existsSync(p) || fs.lstatSync(p).isSymbolicLink()) {
        if (fs.lstatSync(p).isSymbolicLink() && fs.readlinkSync(p) === target) continue;
        fs.rmSync(p, { recursive: true, force: true });
      }
    } catch {}
    try {
      fs.symlinkSync(target, p);
    } catch {}
  }
}

function moveIfMissing(src, dst) {
  if (fs.existsSync(dst) || !fs.existsSync(src)) return false;
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  try {
    fs.renameSync(src, dst);
    return true;
  } catch {}
  return false;
}

function cmpVersions(a, b) {
  const pa = a.split('.').map(Number);
  const pb = b.split('.').map(Number);
  for (let i = 0; i < 3; i++) {
    if (pa[i] !== pb[i]) return pa[i] < pb[i] ? -1 : 1;
  }
  return 0;
}

function realBinary(p) {
  try {
    return fs.statSync(p).isFile() && !fs.lstatSync(p).isSymbolicLink();
  } catch {
    return false;
  }
}

function binaryVersion(bin) {
  try {
    const r = spawnSync(bin, ['--version'], { encoding: 'utf8', timeout: 30000 });
    const v = (r.stdout || '').trim().split('\n')[0].trim();
    return /^\d+\.\d+\.\d+$/.test(v) ? v : null;
  } catch {
    return null;
  }
}

// Keep one shared binary copy; returns { path, version } or null when no
// usable copy exists anywhere yet (first launch then downloads for its HOME).
function ensureSharedBinary() {
  let sharedBest = null;
  if (realBinary(SHARED_BIN)) {
    const v = binaryVersion(SHARED_BIN) || (() => {
      try { return fs.readFileSync(SHARED_BIN_VERSION, 'utf8').trim() || null; } catch { return null; }
    })();
    if (v) {
      sharedBest = { path: SHARED_BIN, version: v };
    }
  }

  let best = sharedBest;
  for (const base of [DATA_ROOT, LEGACY_ROOT]) {
    for (const n of NUMS) {
      const p = path.join(base, n, 'home', '.config', 'manicode', 'freebuff');
      if (!realBinary(p)) continue;
      const v = binaryVersion(p);
      if (!v) continue;
      if (!best || cmpVersions(best.version, v) < 0) best = { path: p, version: v };
    }
  }
  if (!best) return null;
  if (!sharedBest || best.path !== SHARED_BIN || cmpVersions(sharedBest.version, best.version) < 0) {
    try {
      fs.mkdirSync(path.dirname(SHARED_BIN), { recursive: true });
      if (best.path !== SHARED_BIN) {
        fs.copyFileSync(best.path, SHARED_BIN);
        fs.chmodSync(SHARED_BIN, 0o755);
      }
      fs.writeFileSync(SHARED_BIN_VERSION, `${best.version}\n`);
      return { path: SHARED_BIN, version: best.version };
    } catch {
      return sharedBest;
    }
  }
  return sharedBest;
}

export function ensureMetadata(dir, shared) {
  const metaPath = path.join(dir, 'freebuff-metadata.json');
  const expectedTarget = `${process.platform}-${process.arch}`;
  let currentEntry = null;
  try {
    currentEntry = fs.lstatSync(metaPath);
  } catch (error) {
    if (error?.code !== 'ENOENT') return false;
  }

  // Only read an existing regular metadata file. In particular, never follow
  // a symlink leaf while deciding whether reconciliation is needed.
  if (currentEntry?.isFile()) {
    try {
      const cur = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
      if (cur.version === shared.version && cur.target === expectedTarget) return false;
    } catch {}
  }

  const content = `${JSON.stringify({ version: shared.version, target: expectedTarget }, null, 2)}\n`;
  fs.mkdirSync(dir, { recursive: true });
  const tmp = path.join(dir, `.freebuff-metadata.json.tmp-${process.pid}-${randomUUID()}`);
  try {
    // Publish through a new regular file in the same directory, then rename
    // over the leaf. rename replaces a symlink directory entry; it does not
    // follow the symlink target.
    fs.writeFileSync(tmp, content, { flag: 'wx', mode: 0o600 });
    fs.renameSync(tmp, metaPath);
    return true;
  } catch {
    return false;
  } finally {
    try {
      fs.rmSync(tmp, { force: true });
    } catch {}
  }
}

// Point a HOME without its own binary at the shared copy (+ matching
// metadata so the launcher accepts it without re-downloading). Real binaries
// and their future background updates are left alone.
function linkSharedBinary(home, shared) {
  const dir = path.join(home, '.config', 'manicode');
  const bin = path.join(dir, 'freebuff');
  let linked = false;
  try {
    const st = fs.lstatSync(bin);
    if (!st.isSymbolicLink()) return false;
    if (fs.readlinkSync(bin) !== shared.path) {
      fs.rmSync(bin, { force: true });
      fs.symlinkSync(shared.path, bin);
      linked = true;
    }
  } catch {
    try {
      fs.mkdirSync(dir, { recursive: true });
      fs.symlinkSync(shared.path, bin);
      linked = true;
    } catch {
      return false;
    }
  }
  const metaUpdated = ensureMetadata(dir, shared);
  return linked || metaUpdated;
}

function ensureShared() {
  let migrated = 0;
  const repoShared = path.join(REPO_DATA_ROOT, 'shared');
  for (const rel of SHARED_FILES) {
    const dst = path.join(SHARED_ROOT, rel);
    if (fs.existsSync(dst)) continue;
    if (moveIfMissing(path.join(repoShared, rel), dst)) {
      migrated++;
      continue;
    }
    const src = path.join(LEGACY_ROOT, 'shared', rel);
    if (copyIfMissing(src, dst, !rel.endsWith('.json'))) migrated++;
  }
  fs.mkdirSync(path.join(SHARED_ROOT, 'history', 'projects'), { recursive: true });
  return migrated;
}

function ensureHome(n, shared) {
  const home = path.join(DATA_ROOT, n, 'home');
  const repoHome = path.join(REPO_DATA_ROOT, n, 'home');
  const legacy = path.join(LEGACY_ROOT, n, 'home');
  let migrated = 0;
  if (moveIfMissing(repoHome, home)) {
    migrated++;
  } else if (fs.existsSync(repoHome)) {
    for (const rel of HOME_FILES) {
      if (copyIfMissing(path.join(repoHome, rel), path.join(home, rel))) migrated++;
    }
  }
  fs.mkdirSync(home, { recursive: true });
  const sharedMigrated = ensureShared();
  for (const rel of HOME_FILES) {
    if (copyIfMissing(path.join(legacy, rel), path.join(home, rel))) migrated++;
  }
  ensureHomeLinks(home);
  if (shared && linkSharedBinary(home, shared)) migrated++;
  // Drop download residue possibly carried over by the move.
  try {
    const dir = path.join(home, '.config', 'manicode');
    for (const e of fs.readdirSync(dir)) {
      if (e.endsWith('.part') || e === '.freebuff-download-temp') {
        fs.rmSync(path.join(dir, e), { recursive: true, force: true });
      }
    }
  } catch {}
  return { migrated: migrated + sharedMigrated };
}

function cleanupRepoData() {
  // Remove the old in-repo data root once every number has moved out and
  // no unmigrated HOME_FILES remain in REPO_DATA_ROOT.
  try {
    if (!fs.existsSync(REPO_DATA_ROOT)) return false;
    for (const n of NUMS) {
      if (!fs.existsSync(path.join(DATA_ROOT, n, 'home', '.config', 'manicode', 'credentials.json'))) return false;
      const repoHome = path.join(REPO_DATA_ROOT, n, 'home');
      if (fs.existsSync(repoHome)) {
        for (const rel of HOME_FILES) {
          const repoFile = path.join(repoHome, rel);
          const dstFile = path.join(DATA_ROOT, n, 'home', rel);
          if (fs.existsSync(repoFile) && !fs.existsSync(dstFile)) return false;
        }
      }
    }
    fs.rmSync(REPO_DATA_ROOT, { recursive: true, force: true });
    return true;
  } catch {
    return false;
  }
}

function ensureLauncher() {
  const launcher = path.join(ROOT, '.tools', 'npm', 'bin', 'freebuff');
  try {
    const st = fs.statSync(launcher);
    if (st.isFile()) return false;
    fs.rmSync(launcher, { recursive: true, force: true });
  } catch {}
  fs.mkdirSync(path.join(ROOT, '.tools', 'npm'), { recursive: true });
  const r = spawnSync('npm', ['install', '-g', '--prefix', path.join(ROOT, '.tools', 'npm'), 'freebuff@latest'], {
    cwd: ROOT,
    stdio: 'inherit',
  });
  if (r.status !== 0) {
    console.error('freebuff launcher install failed');
    process.exit(r.status ?? 1);
  }
  return true;
}

function ensureWrappers() {
  let wrote = 0;
  for (const n of NUMS) {
    const p = path.join(ROOT, `freebuff-${n}`);
    const content = wrapperScript(n);
    let cur = null;
    try {
      cur = fs.readFileSync(p, 'utf8');
    } catch {}
    if (cur !== content) {
      fs.writeFileSync(p, content, { mode: 0o755 });
      try {
        fs.chmodSync(p, 0o755);
      } catch {}
      wrote++;
    }
  }
  return wrote;
}

function ensureMirror() {
  let wrote = 0;
  try {
    for (const rel of MIRRORED) {
      const src = path.join(ROOT, rel);
      const dst = path.join(MIRROR_ROOT, rel);
      const content = fs.readFileSync(src, 'utf8');
      try {
        const st = fs.lstatSync(dst);
        if (st.isSymbolicLink()) {
          fs.rmSync(dst, { force: true });
        } else if (st.isFile()) {
          const cur = fs.readFileSync(dst, 'utf8');
          if (cur === content) continue;
        }
      } catch {}
      fs.mkdirSync(path.dirname(dst), { recursive: true });
      const tmp = `${dst}.tmp-${process.pid}-${Date.now()}`;
      fs.writeFileSync(tmp, content);
      fs.renameSync(tmp, dst);
      wrote++;
    }
  } catch {}
  return wrote;
}

export function parseArgs(argv = process.argv.slice(2)) {
  if (argv.length === 0) {
    return { mode: 'full' };
  }
  if (argv[0] === '--ensure') {
    if (argv.length === 2 && NUMS.includes(argv[1])) {
      return { mode: 'ensure', num: argv[1] };
    }
    const target = argv.length > 1 ? argv.slice(1).join(' ') : '<missing>';
    throw new Error(`freebuff setup: invalid --ensure selector '${target}'. Expected one of: ${NUMS.join(', ')}`);
  }
  throw new Error(`freebuff setup: unrecognized argument(s) '${argv.join(' ')}'. Usage: freebuff-setup.mjs [--ensure 1..8]`);
}

export function run(argv = process.argv.slice(2)) {
  const parsed = parseArgs(argv);
  if (parsed.mode === 'ensure') {
    ensureShared();
    ensureHome(parsed.num, ensureSharedBinary());
    ensureLauncher();
    return { mode: 'ensure', num: parsed.num };
  }

  const shared = ensureSharedBinary();
  let totalMigrated = 0;
  for (const n of NUMS) totalMigrated += ensureHome(n, shared).migrated;
  const repoCleaned = cleanupRepoData();
  const launcherInstalled = ensureLauncher();
  const wrappersWrote = ensureWrappers();
  const mirrored = ensureMirror();
  const summary = `freebuff setup: migrated=${totalMigrated} repo-data-removed=${repoCleaned} launcher=${launcherInstalled ? 'installed' : 'ok'} wrappers=${wrappersWrote} mirror=${mirrored} (re)wrote`;
  console.log(summary);
  return {
    mode: 'full',
    migrated: totalMigrated,
    repoCleaned,
    launcherInstalled,
    wrappersWrote,
    mirrored,
    summary,
  };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    run();
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
}
