import assert from 'node:assert/strict';
import { createRiscv64DecodedInstruction } from '../../js/targets/architecture/riscv64/decoded-instruction.js';
import { normalizeRiscv64Instruction } from '../../js/targets/architecture/riscv64/effects/common.js';
import { liftRiscv64ControlEffects } from '../../js/targets/architecture/riscv64/effects/control.js';
import { liftRiscv64IntegerEffects } from '../../js/targets/architecture/riscv64/effects/integer.js';
import { liftRiscv64MemoryEffects } from '../../js/targets/architecture/riscv64/effects/memory.js';
const forgedWithoutBytes={contractVersion:'riscv64-decoded-instruction/v1',instructionId:'issue-5049:forged-no-bytes',origin:{instructionIds:['issue-5049:forged-no-bytes']},mode:'rv64imc',address:0x1000n,size:4,fields:{supported:true,compressed:false,op:'addi',rd:'x1',rs1:'x0',imm:123n}};
assert.throws(()=>normalizeRiscv64Instruction(forgedWithoutBytes),/riscv64-decoded-instruction-byte-length-mismatch/);
assert.throws(()=>liftRiscv64IntegerEffects(forgedWithoutBytes),/riscv64-decoded-instruction-byte-length-mismatch/);
const nop={contractVersion:'riscv64-decoded-instruction/v1',instructionId:'issue-5049:nop',origin:{instructionIds:['issue-5049:nop']},mode:'rv64imc',address:0x1000n,size:4,rawBytes:new Uint8Array([0x13,0,0,0]),fields:{supported:true,compressed:false,op:'addi',rd:'x5',rs1:'x7',imm:999n}};
const n=normalizeRiscv64Instruction(nop); assert.equal(n.fields.rd,'x0');assert.equal(n.fields.rs1,'x0');assert.equal(n.fields.imm,0n);assert.equal(liftRiscv64IntegerEffects(nop).operations.some(o=>o.kind==='register-write'),false);
const forgedMemory={...nop,instructionId:'issue-5049:store',origin:{instructionIds:['issue-5049:store']},fields:{supported:true,compressed:false,op:'sd',kind:'store',rs1:'x1',rs2:'x2',imm:64n,memoryWidthBits:64}};assert.equal(liftRiscv64MemoryEffects(forgedMemory),null);
const forgedBranch={...nop,instructionId:'issue-5049:branch',origin:{instructionIds:['issue-5049:branch']},fields:{supported:true,compressed:false,op:'beq',rs1:'x1',rs2:'x2',imm:0x400n}};assert.equal(liftRiscv64ControlEffects(forgedBranch),null);
const unsupported={...nop,instructionId:'issue-5049:unsupported',origin:{instructionIds:['issue-5049:unsupported']},rawBytes:new Uint8Array([0x53,0,0,0]),fields:{supported:true,compressed:false,op:'addi',rd:'x1',rs1:'x0',imm:1n}};assert.equal(normalizeRiscv64Instruction(unsupported).fields.supported,false);assert.equal(liftRiscv64IntegerEffects(unsupported),null);
const canonical=createRiscv64DecodedInstruction({address:0x2000n,size:4,rawBytes:new Uint8Array([0x93,0x00,0xb0,0x07]),mode:'rv64imc',instructionId:'issue-5049:canonical',origin:{instructionIds:['issue-5049:canonical']}});const rn=normalizeRiscv64Instruction(canonical);assert.equal(rn.fields.supported,true);assert.equal(rn.fields.rd,'x1');assert.equal(rn.fields.imm,123n);assert.equal(rn.instructionId,canonical.instructionId);assert.deepEqual(rn.origin,canonical.origin);const ce=liftRiscv64IntegerEffects(canonical);assert.equal(ce.completeness,'exact');assert.equal(ce.operations.some(o=>o.kind==='register-write'),true);
console.log('issue-5049-riscv64-structured-normalization-authority: PASS');
