import assert from 'node:assert/strict';
import { createX86DecodedInstruction } from '../../js/targets/architecture/x86_64/decoded-instruction.js';
import { liftX86MachineEffects } from '../../js/targets/architecture/x86_64/effects/index.js';
import { createCapstoneX86Session } from '../phase5/helpers/capstone-session.mjs';
import { X86_LONG64_SIMD_DENOMINATOR_ID,X86_LONG64_SIMD_EXACT_FORMS,X86_LONG64_SIMD_OWNED_REMAINING,X86_LONG64_SIMD_SHARED_BLOCKERS,validateX86Long64SimdDenominator } from '../../tools/validation/machine-effects/x86-long64-simd-denominator.mjs';
import { effects,reg,imm,legacy,vex128,vex256,evex,operations } from './helpers/x86-long64-fp-simd.mjs';
const d=validateX86Long64SimdDenominator();assert.equal(d.denominatorId,X86_LONG64_SIMD_DENOMINATOR_ID);assert.equal(d.exactFormCount,125);assert.equal(d.ownedRemainingCount,0);assert.equal(d.sharedBlockerCount,5);assert.equal(d.closed,false);assert.equal(X86_LONG64_SIMD_OWNED_REMAINING.length,0);
const pp=new Map([['movaps',0],['movups',0],['movapd',1],['movupd',1],['movdqa',1],['movdqu',2],['movd',1],['movq',1],['andps',0],['andpd',1],['pand',1],['orps',0],['orpd',1],['por',1],['xorps',0],['xorpd',1],['pxor',1],['paddb',1],['paddw',1],['paddd',1],['paddq',1],['psubb',1],['psubw',1],['psubd',1],['psubq',1],['pcmpeqb',1],['pcmpeqw',1],['pcmpeqd',1],['pcmpgtb',1],['pcmpgtw',1],['pcmpgtd',1],['psllw',1],['pslld',1],['psllq',1],['psrlw',1],['psrld',1],['psrlq',1],['psraw',1],['psrad',1],['pshufd',1],['punpckldq',1],['pandn',1]]);
function prefix(form){if(form.prefixClass==='legacy')return legacy();const code=form.kind==='vector-state'?0:pp.get(form.mnemonic.replace(/^v/,''));return form.vectorWidthBits===256?vex256(code):vex128(code);}
function v(n,w){return reg(`${w===256?'ymm':'xmm'}${n}`);}
function operands(form){const base=form.mnemonic.replace(/^v/,''),w=form.vectorWidthBits,p=form.prefixClass;if(form.kind==='vector-state')return[];if(form.kind==='full-move')return[v(0,w),v(1,w)];if(form.kind==='scalar-integer-move')return[reg('xmm0'),reg(base==='movd'?'eax':'rax')];if(form.kind==='packed-shift')return p==='legacy'?[v(0,w),imm(3)]:[v(0,w),v(1,w),imm(3)];if(form.kind==='lane-map')return base==='pshufd'?[v(0,w),v(1,w),imm(0x1b)]:(p==='legacy'?[v(0,w),v(1,w)]:[v(0,w),v(1,w),v(2,w)]);if(form.kind==='and-not')return p==='legacy'?[v(0,w),v(1,w)]:[v(0,w),v(1,w),v(2,w)];return p==='legacy'?[v(0,w),v(1,w)]:[v(0,w),v(1,w),v(2,w)];}
for(const form of X86_LONG64_SIMD_EXACT_FORMS){const b=effects(form.mnemonic,operands(form),prefix(form));assert.ok(b,form.id);assert.ok(['exact','exact-with-intrinsic'].includes(b.completeness),`${form.id}:${b.unknownEffects?.reason}`);assert.equal(b.metadata.family,'simd',form.id);}
const oldSynthetic=effects('vpaddd',[reg('ymm0'),reg('ymm1'),reg('ymm2')],vex256(0));assert.equal(oldSynthetic.completeness,'partial');assert.match(oldSynthetic.unknownEffects.reason,/vector-width-unmodelled/);
const badXorPfx=vex128(1),badXor=effects('vxorps',[reg('xmm0'),reg('xmm1'),reg('xmm2')],badXorPfx,[...badXorPfx.vector.bytes,0x57,0xc2]);assert.equal(badXor.completeness,'partial');assert.match(badXor.unknownEffects.reason,/prefix-family-mismatch/);
const badPandnPfx=vex256(0),badPandn=effects('vpandn',[reg('ymm0'),reg('ymm1'),reg('ymm2')],badPandnPfx,[...badPandnPfx.vector.bytes,0xdf,0xc2]);assert.equal(badPandn.completeness,'partial');assert.match(badPandn.unknownEffects.reason,/prefix-family-mismatch/);
const malformed=effects('vxorps',[reg('xmm0'),reg('xmm1'),reg('xmm2')],evex(0xf1,0x78,0x08));assert.equal(malformed.completeness,'partial');assert.match(malformed.unknownEffects.reason,/prefix-metadata-malformed/);
const evexMasked=effects('vxorps',[reg('xmm0'),reg('xmm1'),reg('xmm2')],evex(0xf1,0x7c,0x81));assert.equal(evexMasked.completeness,'partial');assert.equal(evexMasked.metadata.maskRegister,'k1');assert.equal(evexMasked.metadata.maskSemantics,'zero');
const unownedEvex=effects('vpmulld',[reg('xmm0'),reg('xmm1'),reg('xmm2')],evex());assert.equal(unownedEvex,null);
const vzeroall=effects('vzeroall',[],vex256(0),[0xc5,0xfc,0x77]);assert.ok(['exact','exact-with-intrinsic'].includes(vzeroall.completeness));assert.equal(vzeroall.metadata.extendedVectorStateModeled,true);assert.equal(vzeroall.metadata.bits128To511,'zero');
const emms=effects('emms',[],legacy(),[0x0f,0x77]);assert.ok(['exact','exact-with-intrinsic'].includes(emms.completeness));assert.equal(emms.metadata.mmxX87AliasModeled,true);assert.equal(emms.metadata.x87TagWord,'all-empty');
const legacyXor=effects('xorps',[reg('xmm0'),reg('xmm1')],legacy());assert.ok(operations(legacyXor,'value').some((op)=>op.opcode==='insert'&&op.metadata?.writePolicy==='legacy-preserve-upper-128'));
const vexXor=effects('vxorps',[reg('xmm0'),reg('xmm1'),reg('xmm2')],vex128(0));assert.ok(operations(vexXor,'value').some((op)=>op.opcode==='zext'&&op.metadata?.toBits===256));
const capstone=await createCapstoneX86Session();try{for(const [name,bytes] of Object.entries({vpaddd:[0xc5,0xf5,0xfe,0xc2],vpcmpeqd:[0xc5,0xf5,0x76,0xc2],vpslld:[0xc5,0xf5,0x72,0xf1,0x03],vpshufd:[0xc5,0xfd,0x70,0xc1,0x1b],vpunpckldq:[0xc5,0xf5,0x62,0xc2]})){const raw=capstone.decode(bytes,0x710000n)[0];assert.equal(raw.mnemonic,name);const b=liftX86MachineEffects(raw,{instructionId:`capstone:${name}`});assert.ok(['exact','exact-with-intrinsic'].includes(b.completeness),`${name}:${b.unknownEffects?.reason}`);}const zmm=capstone.decode([0x62,0xf1,0x7c,0x48,0x57,0xc0],0x710100n)[0];assert.equal(zmm.mnemonic,'vxorps');const decodedZmm=createX86DecodedInstruction(zmm);const zmm0=decodedZmm.detail.operands[0]?.register;assert.equal(zmm0?.id,'zmm0');assert.equal(zmm0?.viewBits,512);assert.equal(Array.isArray(zmm0?.compositeParts),true);}finally{capstone.close();}
assert.equal(X86_LONG64_SIMD_SHARED_BLOCKERS.length,5);
console.log(`x86 long64 SIMD denominator: ${d.exactFormCount} exact forms + ${d.ownedRemainingCount} owned + ${d.sharedBlockerCount} shared blockers: PASS`);
