import assert from 'node:assert/strict';
import { createX86DecodedInstruction } from '../../js/targets/architecture/x86_64/decoded-instruction.js';
import { createCapstoneX86Session } from '../phase5/helpers/capstone-session.mjs';
import { X86_LONG64_FP_DENOMINATOR_ID,X86_LONG64_FP_EXACT_FORMS,X86_LONG64_FP_SHARED_BLOCKERS,validateX86Long64FpDenominator } from '../../tools/validation/machine-effects/x86-long64-fp-denominator.mjs';
import { effects,reg,legacy,vex128,vex256,evex,operations } from './helpers/x86-long64-fp-simd.mjs';
const d=validateX86Long64FpDenominator();assert.equal(d.denominatorId,X86_LONG64_FP_DENOMINATOR_ID);assert.equal(d.exactFormCount,68);assert.equal(d.ownedRemainingCount,0);assert.equal(d.sharedBlockerCount,3);assert.equal(d.closed,false);
const pp=new Map([['movss',2],['movsd',3],['addss',2],['addsd',3],['subss',2],['subsd',3],['mulss',2],['mulsd',3],['divss',2],['divsd',3],['sqrtss',2],['sqrtsd',3],['ucomiss',0],['ucomisd',1],['comiss',0],['comisd',1],['addps',0],['addpd',1],['subps',0],['subpd',1],['mulps',0],['mulpd',1],['divps',0],['divpd',1],['cvtss2sd',2],['cvtsd2ss',3],['cvtsi2ss',2],['cvtsi2sd',3],['cvttss2si',2],['cvttsd2si',3]]);
function prefix(form){if(form.prefixClass==='legacy')return legacy();const code=pp.get(form.mnemonic.replace(/^v/,''));return form.vectorWidthBits===256?vex256(code):vex128(code);}
function v(n,w){return reg(`${w===256?'ymm':'xmm'}${n}`);}
function operands(form){const base=form.mnemonic.replace(/^v/,''),p=form.prefixClass,w=form.vectorWidthBits;if(form.kind==='packed-arithmetic')return p==='legacy'?[v(0,w),v(1,w)]:[v(0,w),v(1,w),v(2,w)];if(form.kind==='scalar-compare')return [reg('xmm0'),reg('xmm1')];if(form.kind==='conversion'){if(base.startsWith('cvtt'))return [reg('rax'),reg('xmm1')];if(base.startsWith('cvtsi'))return p==='legacy'?[reg('xmm0'),reg('rax')]:[reg('xmm0'),reg('xmm1'),reg('rax')];return p==='legacy'?[reg('xmm0'),reg('xmm1')]:[reg('xmm0'),reg('xmm1'),reg('xmm2')];}return p==='legacy'?[reg('xmm0'),reg('xmm1')]:[reg('xmm0'),reg('xmm1'),reg('xmm2')];}
for(const form of X86_LONG64_FP_EXACT_FORMS){const b=effects(form.mnemonic,operands(form),prefix(form));assert.ok(b,form.id);assert.ok(['exact','exact-with-intrinsic'].includes(b.completeness),`${form.id}:${b.unknownEffects?.reason}`);assert.equal(b.metadata.family,'fp',form.id);if(form.fpState==='mxcsr'){assert.ok(operations(b,'register-read').some((op)=>op.register.registerId==='mxcsr'),`${form.id}:mxcsr-read`);assert.ok(operations(b,'register-write').some((op)=>op.register.registerId==='mxcsr'),`${form.id}:mxcsr-write`);}}
const badPp=effects('vaddps',[reg('xmm0'),reg('xmm1'),reg('xmm2')],vex128(1));assert.equal(badPp.completeness,'partial');assert.match(badPp.unknownEffects.reason,/prefix-family-mismatch/);
const malformed=effects('vaddps',[reg('xmm0'),reg('xmm1'),reg('xmm2')],evex(0xf1,0x7c,0x68));assert.equal(malformed.completeness,'partial');assert.match(malformed.unknownEffects.reason,/prefix-metadata-malformed/);
const evexLow=effects('vaddps',[reg('xmm0'),reg('xmm1'),reg('xmm2')],evex());assert.equal(evexLow.completeness,'partial');assert.ok(evexLow.metadata.sharedDependencyRequired.includes('x86-physical-zmm0-31'));
const x87=effects('fldz',[],legacy());assert.equal(x87.completeness,'partial');assert.ok(x87.metadata.sharedDependencyRequired.includes('x86-x87-physical-state'));
assert.equal(X86_LONG64_FP_SHARED_BLOCKERS.some(({id})=>id==='vex-maxvl-alias'),true);
const capstone=await createCapstoneX86Session();try{const zmm=capstone.decode([0x62,0xf1,0x7c,0x48,0x58,0xc1],0x700000n)[0];assert.equal(zmm.mnemonic,'vaddps');const zmmDecoded=createX86DecodedInstruction(zmm);assert.equal(zmmDecoded.detail.operands[0].register.id,'zmm0');assert.equal(zmmDecoded.detail.operands[0].register.decoderSupplementary,true);assert.equal(zmmDecoded.detail.operands[0].register.modeled,false);const fldz=capstone.decode([0xd9,0xee],0x700100n)[0];assert.equal(fldz.mnemonic,'fldz');assert.throws(()=>createX86DecodedInstruction(fldz),/x86-decoded-instruction-unknown-implicit-write/);}finally{capstone.close();}
console.log(`x86 long64 FP denominator: ${d.exactFormCount} exact forms + ${d.sharedBlockerCount} shared blockers: PASS`);
